export const MDN = {
  grammar:'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Grammar_and_types',
  control:'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Control_flow_and_error_handling',
  loops:'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Loops_and_iteration',
  functions:'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Functions',
  operators:'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Expressions_and_operators',
  numbers:'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Numbers_and_strings',
  dates:'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Representing_dates_times',
  regex:'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_expressions',
  arrays:'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Indexed_collections',
  keyed:'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Keyed_collections',
  objects:'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Working_with_objects',
  classes:'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Using_classes',
  data:'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Data_structures',
  props:'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Enumerability_and_ownership_of_properties',
  prototype:'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Inheritance_and_the_prototype_chain',
  equality:'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Equality_comparisons_and_sameness',
  closures:'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Closures'
};

const R=(cpu=0,heap=0,stack=0,queue=0,dom=0,network=0,native=0,threads=0)=>({cpu,heap,stack,queue,dom,network,native,threads});
const L=(id,topic,title,source,summary,bad,good,code,visual,resources,traps=[],tips=[])=>({
  id,topic,title,source,summary,compare:{bad,good},code,visual,resources,traps,tips,runner:'worker'
});

export const CORE_TOPICS=[
  {id:'foundations',title:'Language foundations',description:'Syntax, declarations, primitives, coercion, operators and equality.'},
  {id:'control',title:'Control flow & iteration',description:'Branches, exceptions, loops and iteration choices.'},
  {id:'functions',title:'Functions, scope & closures',description:'Function forms, lexical scope, this, callbacks, recursion and closures.'},
  {id:'objects',title:'Objects, prototypes & classes',description:'Properties, identity, prototypes, classes and encapsulation.'},
  {id:'collections',title:'Collections & built-ins',description:'Arrays, Map, Set, strings, numbers, dates, regex and binary data.'}
];

export const CORE_LESSONS=[
L('syntax-expressions','foundations','Statements vs expressions',MDN.grammar,
'Expressions produce values; statements perform actions or control flow. Seeing that distinction makes compact JavaScript easier to reason about.',
`let total = 0\ntotal = total + 1\ntotal`,
`let total = 0;\ntotal += 1;\nconsole.log(total);`,
`const price=12; const quantity=3; const total=price*quantity; console.log({price,quantity,total});`,
'flow',R(1,0,1),['Automatic semicolon insertion exists; do not confuse it with “semicolons never matter”.'],['Ask “does this produce a value, or control execution?”']),

L('let-const-var','foundations','var, let and const',MDN.grammar,
'var is function-scoped; let and const are block-scoped. const prevents rebinding, not mutation of an object stored in the binding.',
`var user={name:"Ada"};\nuser=null;`,
`const user={name:"Ada"};\nuser.name="Grace";`,
`const account={balance:10}; account.balance+=5; console.log(account); try { account={}; } catch(e) { console.log(e.name); }`,
'binding',R(1,1,1),['const does not freeze an object.','var can escape a block.'],['Default to const; choose let when the binding itself must change.']),

L('lexical-scope','foundations','Block scope and lexical scope',MDN.grammar,
'Name lookup follows the lexical structure of source code. Inner scopes see outer bindings; outer scopes do not see bindings created only inside.',
`if (ready) { var message="go"; }\nconsole.log(message);`,
`if (ready) { const message="go"; console.log(message); }`,
`const outer="outside"; { const inner="inside"; console.log(outer,inner); } try { console.log(inner); } catch(e) { console.log(e.name); }`,
'scope',R(1,1,2),['A var binding is not block-scoped.'],['Make lifetime visible by using the smallest useful scope.']),

L('hoisting-tdz','foundations','Hoisting and the temporal dead zone',MDN.grammar,
'Declarations are processed before ordinary execution, but let and const cannot be accessed before initialization. Function declarations have their own hoisting behavior.',
`console.log(value);\nlet value=3;`,
`let value=3;\nconsole.log(value);`,
`try { console.log(value); } catch(e) { console.log(e.name); } let value=42; console.log(value);`,
'scope',R(1,1,2),['“Hoisted” does not mean “usable before declaration”.'],['Prefer source order that makes initialization obvious.']),

L('primitive-types','foundations','The seven primitive types',MDN.grammar,
'JavaScript primitives are Boolean, null, undefined, Number, BigInt, String and Symbol. Everything else is an object.',
`const values=[0,"",false,null]; // treating all empty-looking values as equivalent`,
`const state={count:0,label:"",enabled:false,selection:null};`,
`const values=[true,null,undefined,42,42n,"hello",Symbol("id")]; for(const value of values) console.log(String(value),"→",typeof value);`,
'values',R(1,1,1),['typeof null is "object" for historical reasons.','Number and BigInt are distinct numeric types.'],['Use null/undefined deliberately rather than as interchangeable “nothing”.']),

L('primitive-object-identity','foundations','Primitive values vs object identity',MDN.data,
'Primitives are immutable values. Objects are mutable identities, and multiple bindings can reference the same object.',
`const a={score:1}; const b=a; b.score=99;`,
`const a={score:1}; const b={...a,score:99};`,
`let x=10; let y=x; y++; console.log({x,y}); const a={n:10}; const b=a; b.n++; console.log({a,b,same:a===b});`,
'reference',R(1,2,1),['Object assignment copies a reference, not an independent object.'],['Ask whether two bindings should share identity or merely equal data.']),

L('null-undefined','foundations','null and undefined',MDN.grammar,
'undefined commonly means uninitialized/missing; null is an explicit primitive value often used to mean intentionally empty.',
`if (value == null) { /* merged semantics without saying why */ }`,
`if (value === undefined) {}\nif (value === null) {}`,
`const object={}; console.log(object.missing); console.log(null===undefined); console.log(null==undefined);`,
'values',R(1,0,1),['Loose equality intentionally treats null and undefined as equal to each other.'],['Use strict checks when the distinction carries meaning.']),

L('numbers','foundations','Number and floating point',MDN.numbers,
'Number is IEEE-754 double precision. Many decimal fractions cannot be represented exactly, and integer precision is bounded.',
`console.log(0.1+0.2===0.3);`,
`const value=0.1+0.2; console.log(Math.abs(value-0.3)<Number.EPSILON);`,
`const value=0.1+0.2; console.log(value,value===0.3); console.log(Number.isNaN(NaN),Number.isFinite(Infinity),Number.MAX_SAFE_INTEGER);`,
'number',R(1,0,1),['NaN is not equal to itself.','Integers beyond MAX_SAFE_INTEGER may lose precision.'],['Use Number.isNaN/Number.isFinite for precise checks.']),

L('bigint','foundations','BigInt',MDN.numbers,
'BigInt represents integers of arbitrary magnitude. It is a distinct numeric type and cannot be mixed directly with Number arithmetic.',
`const n=9007199254740993+1;`,
`const n=9007199254740993n+1n;`,
`const huge=9007199254740993n; console.log(huge+1n); try { console.log(huge+1); } catch(e) { console.log(e.name); }`,
'number',R(1,1,1),['BigInt is integer-only; it is not arbitrary-precision decimal arithmetic.'],['Choose one numeric domain at a boundary and convert intentionally.']),

L('strings','foundations','Strings and template literals',MDN.numbers,
'Strings are immutable sequences of UTF-16 code units. Template literals make interpolation and multi-line source explicit.',
`const message="Hello "+name+", total: "+total;`,
'const message=`Hello ${name}, total: ${total}`;',
'const name="Ada",items=3; console.log(`Hello ${name}. You have ${items} items.`); console.log("🚀".length);',
'values',R(1,1,1),['String length counts UTF-16 code units, not always user-perceived characters.'],['Use template literals when interpolation clarifies structure.']),

L('symbols','foundations','Symbol',MDN.data,
'Each Symbol is unique and can be used as a property key that cannot collide with ordinary string keys.',
`const metaKey="__metadata__";`,
`const metaKey=Symbol("metadata");`,
`const id=Symbol("id"); const object={[id]:123,id:"public"}; console.log(object.id,object[id],Object.keys(object));`,
'object',R(1,1,1),['Symbol-keyed properties are absent from Object.keys.'],['Use Symbol for unique keys/identity, not merely to “hide” data.']),

L('coercion','foundations','Implicit type coercion',MDN.operators,
'Operators may convert operands between types. The rules are defined but can be surprising when boundary types are uncontrolled.',
`console.log("5"+1);\nconsole.log("5"-1);`,
`const value=Number(input);\nconsole.log(value+1);`,
`console.log("5"+1); console.log("5"-1); console.log(Boolean("")); console.log(Boolean("false"));`,
'coercion',R(1,0,1),['+ can concatenate while - coerces toward number.','The string "false" is truthy.'],['Convert explicitly at boundaries.']),

L('truthy-falsy','foundations','Truthy and falsy',MDN.control,
'Boolean contexts coerce values. false, 0, -0, 0n, empty string, null, undefined and NaN are falsy; objects are truthy.',
`if (!count) console.log("missing");`,
`if (count === undefined) console.log("missing");`,
`for(const value of [false,0,"",null,undefined,NaN,[],{},"0"]) console.log(String(value),"→",Boolean(value));`,
'coercion',R(1,0,1),['Empty arrays and objects are truthy.','!value can accidentally classify 0 or "" as missing.'],['Use truthiness only when all falsy values genuinely mean the same thing.']),

L('equality','foundations','Equality and sameness',MDN.equality,
'JavaScript has multiple sameness algorithms. === avoids most coercion; Object.is differs for NaN and signed zero.',
`if (input == 0) {}`,
`if (Number(input) === 0) {}`,
`console.log(0=="0",0==="0",NaN===NaN,Object.is(NaN,NaN),Object.is(0,-0));`,
'compare',R(1,0,1),['Object.is(NaN,NaN) is true while NaN===NaN is false.'],['Default to strict equality unless coercive semantics are deliberate.']),

L('operators','foundations','Operators and precedence',MDN.operators,
'Operators combine values; precedence and associativity decide grouping when parentheses are absent.',
`const result=a+b*c>limit&&enabled;`,
`const score=a+(b*c);\nconst allowed=(score>limit)&&enabled;`,
`const a=2,b=3,c=4; console.log(a+b*c,(a+b)*c); console.log(true||false&&false,(true||false)&&false);`,
'flow',R(1,0,1),['Readable grouping can be more valuable than relying on memorized precedence.'],['Use parentheses when they reveal intent.']),

L('optional-chaining','foundations','Optional chaining',MDN.operators,
'Optional chaining stops property access/calls when the left side is null or undefined, yielding undefined instead of throwing.',
`const city=user&&user.address&&user.address.city;`,
`const city=user?.address?.city;`,
`const users=[{name:"Ada",address:{city:"London"}},{name:"Lin"}]; for(const user of users) console.log(user.name,user.address?.city);`,
'flow',R(1,0,1),['Overuse can hide unexpectedly missing required data.'],['Use ?. for genuinely optional structure; validate required structure.']),

L('nullish','foundations','Nullish coalescing',MDN.operators,
'?? falls back only for null/undefined. || falls back for every falsy value.',
`const retries=configuredRetries||3;`,
`const retries=configuredRetries??3;`,
`for(const value of [0,"",false,null,undefined]) console.log(value,"||",value||"fallback","??",value??"fallback");`,
'compare',R(1,0,1),['|| replaces legitimate 0, false and empty-string values.'],['Use ?? when absence, not falsiness, should trigger a default.']),

L('destructuring','foundations','Destructuring',MDN.operators,
'Destructuring extracts array elements/object properties into bindings and supports defaults and rest patterns.',
`const name=user.name; const role=user.role;`,
`const {name,role="user"}=user;`,
`const user={name:"Ada",role:"admin",active:true}; const {name,role,...rest}=user; console.log(name,role,rest);`,
'values',R(1,1,1),['Deep destructuring can become less readable than direct property access.'],['Destructure where it makes the data contract clearer.']),

L('spread-rest','foundations','Spread and rest',MDN.operators,
'... expands values in some positions and collects remaining values in others.',
`const copy=object; copy.enabled=true;`,
`const copy={...object,enabled:true};`,
`const values=[1,2,3]; console.log(Math.max(...values)); const [first,...rest]=values; console.log({first,rest});`,
'reference',R(1,2,1),['Object/array spread makes shallow copies.'],['Use rest to express “the remaining values” explicitly.']),

L('if-switch','control','if, else and switch',MDN.control,
'Branching chooses one control-flow path. switch is useful when several branches compare one expression against distinct values.',
`if(status==="new"){} else if(status==="paid"){} else if(status==="sent"){}`,
`switch(status){ case "new": break; case "paid": break; case "sent": break; }`,
`const status="paid"; switch(status){ case "new":console.log("await");break; case "paid":console.log("prepare");break; default:console.log("unknown"); }`,
'flow',R(1,0,1),['switch falls through unless execution exits the case.'],['Choose the shape that makes the decision table obvious.']),

L('exceptions','control','throw, try, catch and finally',MDN.control,
'Exceptions unwind normal execution until handled. finally runs whether or not the try block completes normally.',
`try { parse(data); } catch(e) {}`,
`try { parse(data); } catch(error) { console.error(error); throw error; }`,
`try { throw new TypeError("bad value"); } catch(error) { console.log(error.name,error.message); } finally { console.log("cleanup"); }`,
'stack',R(1,1,2),['Swallowing errors destroys debugging information.'],['Throw Error objects and preserve useful context.']),

L('for-loop','control','Classic for loop',MDN.loops,
'A for loop places initialization, continuation test and afterthought in one header.',
`let i=0; while(i<items.length){ use(items[i]); i++; }`,
`for(let i=0;i<items.length;i++){ use(items[i]); }`,
`for(let i=0;i<5;i++) console.log(i,i*i);`,
'loop',R(2,0,1),['Off-by-one errors come from misunderstanding the continuation condition.'],['Use the loop form that exposes the control variable most clearly.']),

L('while','control','while and do...while',MDN.loops,
'while checks before each iteration; do...while executes the body once before checking.',
`do { process(item); } while(item!=null);`,
`while(item!=null){ process(item); item=next(); }`,
`let n=3; while(n>0){ console.log(n); n--; }`,
'loop',R(2,0,1),['do...while always executes once.'],['Use while when iteration count is driven by state rather than an index.']),

L('break-continue','control','break and continue',MDN.loops,
'break exits a loop; continue skips the remainder of the current iteration.',
`for(const item of items){ if(item.valid){ process(item); } }`,
`for(const item of items){ if(!item.valid) continue; process(item); }`,
`for(let n=1;n<=6;n++){ if(n%2===0) continue; console.log(n); }`,
'loop',R(1,0,1),['Too many control exits can make loop state harder to follow.'],['Guard-style continue can keep the main path flat.']),

L('for-of','control','for...of',MDN.loops,
'for...of consumes an iterable and yields its values.',
`for(let i=0;i<values.length;i++) console.log(values[i]);`,
`for(const value of values) console.log(value);`,
`for(const character of "JS🚀") console.log(character);`,
'iteration',R(1,0,1),['Plain object records are not iterable by default.'],['Use for...of when you want values rather than indexes.']),

L('for-in','control','for...in',MDN.loops,
'for...in enumerates enumerable string property keys, including inherited enumerable keys.',
`for(const index in array) console.log(array[index]);`,
`for(const value of array) console.log(value);`,
`const proto={inherited:true}; const object=Object.create(proto); object.own=1; for(const key in object) console.log(key);`,
'properties',R(1,0,1),['for...in is usually not the right tool for array values.'],['For own object keys, Object.keys/Object.entries are often clearer.']),

L('function-forms','functions','Function declarations and expressions',MDN.functions,
'Functions are first-class values. Declarations and expressions differ syntactically and in initialization/hoisting behavior.',
`run(); const run=function(){};`,
`function run(){} run();`,
`function add(a,b){return a+b;} const multiply=function(a,b){return a*b;}; console.log(add(2,3),multiply(2,3));`,
'function',R(1,1,2),['Function expressions stored in let/const follow binding initialization rules.'],['Choose a form for readability and lifecycle, not style dogma.']),

L('arrow-functions','functions','Arrow functions',MDN.functions,
'Arrows are compact function expressions without their own this, arguments, super or new.target.',
`const counter={value:1,later(){setTimeout(function(){console.log(this.value)},0)}};`,
`const counter={value:1,later(){setTimeout(()=>console.log(this.value),0)}};`,
`const values=[1,2,3]; console.log(values.map(value=>value*2));`,
'this',R(1,1,2,1),['Arrow functions are not constructors.','Lexical this is wrong when a method needs dynamic receiver binding.'],['Use arrows for callbacks and lexical this; use methods/functions when dynamic this matters.']),

L('parameters','functions','Parameters: defaults and rest',MDN.functions,
'Default parameters provide fallback values; rest parameters gather remaining arguments into an array.',
`function sum(){ return Array.from(arguments).reduce((a,b)=>a+b,0); }`,
`function sum(...values){ return values.reduce((a,b)=>a+b,0); }`,
`function greet(name="friend",...tags){ console.log(name,tags); } greet(); greet("Ada","admin","online");`,
'function',R(1,1,2),['Defaults apply to undefined, not null.'],['Prefer rest parameters over arguments in modern code.']),

L('return','functions','Return values and early return',MDN.functions,
'return ends the current function invocation. Falling off the end returns undefined.',
`function parse(value){ if(value){ if(typeof value==="string") return value.trim(); } }`,
`function parse(value){ if(typeof value!=="string") return ""; return value.trim(); }`,
`function classify(n){ if(n<0)return"negative"; if(n===0)return"zero"; return"positive"; } console.log([-1,0,2].map(classify));`,
'flow',R(1,0,2),['No explicit return means undefined.'],['Early return often clarifies preconditions and exceptional cases.']),

L('lexical-environment','functions','Lexical environments',MDN.closures,
'A function resolves free variables from where it was created, not where it is later called.',
`let rate=1; function convert(x){ return x*rate; }`,
`function makeConverter(rate){ return value=>value*rate; }`,
`const rate=2; function outer(){ const rate=3; return()=>rate; } const read=outer(); console.log(read(),rate);`,
'closure',R(1,2,2),['Call location does not change lexical variable resolution.'],['Capturing configuration can make a function dependency explicit.']),

L('closures','functions','Closures',MDN.closures,
'A closure preserves access to surrounding lexical bindings even after the outer execution context has finished.',
`let count=0; function increment(){ return ++count; }`,
`function makeCounter(){ let count=0; return()=>++count; }`,
`function makeCounter(start=0){ let count=start; return{next(){return++count},read(){return count}}; } const counter=makeCounter(10); console.log(counter.next(),counter.next(),counter.read());`,
'closure',R(1,3,2),['Captured objects can stay reachable as long as the closure lives.','Separate outer calls create separate captured environments.'],['Use closures for private state when that model is simpler than a class.']),

L('closures-loops','functions','Closures inside loops',MDN.closures,
'Block-scoped loop bindings create a fresh binding for each iteration, avoiding the classic shared-var closure problem.',
`const fns=[]; for(var i=0;i<3;i++) fns.push(()=>i);`,
`const fns=[]; for(let i=0;i<3;i++) fns.push(()=>i);`,
`const a=[]; for(var i=0;i<3;i++)a.push(()=>i); console.log(a.map(fn=>fn())); const b=[]; for(let j=0;j<3;j++)b.push(()=>j); console.log(b.map(fn=>fn()));`,
'closure',R(1,2,2),['var creates one shared function-scoped binding here.'],['Use let/const iteration bindings when closures capture the iteration value.']),

L('this','functions','this and call-site binding',MDN.functions,
'For ordinary functions, this is generally determined by how the function is called, not where it is defined.',
`const fn=user.getName; fn();`,
`const fn=user.getName.bind(user); fn();`,
`function show(){return this?.name} const a={name:"Ada",show},b={name:"Lin",show}; console.log(a.show(),b.show());`,
'this',R(1,1,2),['Extracting a method can lose its receiver.'],['Read the call expression first when reasoning about this.']),

L('call-apply-bind','functions','call, apply and bind',MDN.functions,
'call/apply invoke with an explicit this value; bind creates a new function with this and optionally leading arguments fixed.',
`handler=object.handle;`,
`handler=object.handle.bind(object);`,
`function describe(prefix,suffix){return prefix+this.name+suffix} const user={name:"Ada"}; console.log(describe.call(user,"[","]")); console.log(describe.apply(user,["<",">"])); console.log(describe.bind(user,"(",")")());`,
'this',R(1,2,2),['bind creates a new function; it does not modify the original.'],['Prefer simpler data flow when manual this rebinding is avoidable.']),

L('recursion','functions','Recursion and stack frames',MDN.functions,
'Recursive calls push execution contexts until a base case stops recursion; excessive depth can exhaust the stack.',
`function factorial(n){ return n*factorial(n-1); }`,
`function factorial(n){ if(n<=1)return 1; return n*factorial(n-1); }`,
`function factorial(n){ console.log("enter",n); if(n<=1)return 1; const result=n*factorial(n-1); console.log("leave",n,result); return result; } console.log(factorial(5));`,
'stack',R(2,1,3),['Unbounded recursion can overflow the call stack.'],['Make the base case and decreasing problem size obvious.']),

L('higher-order','functions','Higher-order functions and callbacks',MDN.functions,
'Functions are values, so they can be passed into and returned from other functions.',
`for(const item of items){ if(item.active) output.push(item.name); }`,
`const names=items.filter(x=>x.active).map(x=>x.name);`,
`function twice(fn){return value=>fn(fn(value))} const double=x=>x*2; console.log(twice(double)(3));`,
'function',R(1,2,2),['Callback chains become opaque when each step has side effects or hidden state.'],['Name nontrivial callbacks when the transformation has a domain concept.']),

L('object-literals','objects','Object literals and property access',MDN.objects,
'Objects store keyed properties. Dot notation uses identifier-like names; brackets accept computed property keys.',
`object.user-name`,
`object["user-name"]`,
`const key="role"; const user={name:"Ada",[key]:"admin"}; console.log(user.name,user[key]);`,
'object',R(1,2,1),['Dot notation cannot express every property name.'],['Use brackets when a key is computed or not a valid identifier.']),

L('object-methods','objects','Object methods',MDN.objects,
'Functions stored on objects can operate with the object as receiver when invoked as methods.',
`const user={name:name,greet:function(){return this.name}};`,
`const user={name,greet(){return this.name}};`,
`const account={balance:10,deposit(amount){this.balance+=amount; return this.balance}}; console.log(account.deposit(5));`,
'object',R(1,2,2),['Method shorthand still uses call-site this semantics.'],['Use methods when behavior naturally belongs with object state.']),

L('property-enumeration','objects','Enumerable, own and inherited properties',MDN.props,
'Properties differ by ownership and enumerability; traversal APIs select different subsets.',
`for(const key in object) copy[key]=object[key];`,
`for(const [key,value] of Object.entries(object)) copy[key]=value;`,
`const base={inherited:1}; const object=Object.create(base); object.visible=2; Object.defineProperty(object,"hidden",{value:3,enumerable:false}); console.log(Object.keys(object)); console.log(Reflect.ownKeys(object)); for(const key in object)console.log("for-in",key);`,
'properties',R(1,2,2),['for...in includes inherited enumerable string keys.','Object.keys excludes symbols and non-enumerable own properties.'],['Choose traversal semantics deliberately.']),

L('descriptors','objects','Property descriptors',MDN.objects,
'Properties carry descriptor attributes such as writable, enumerable and configurable, or getter/setter functions.',
`object.id=42;`,
`Object.defineProperty(object,"id",{value:42,writable:false,enumerable:true});`,
`const object = {};
Object.defineProperty(object, "id", {
  value: 42,
  writable: false,
  enumerable: true
});

console.log(Object.getOwnPropertyDescriptor(object, "id"));

try {
  object.id = 99;
} catch (error) {
  console.log("write blocked:", error.name);
}

console.log("id:", object.id);`,
'properties',R(1,2,2),['Assignment syntax hides descriptor defaults.'],['Use descriptors only when those low-level semantics matter.']),

L('prototype-chain','objects','Prototype chain lookup',MDN.prototype,
'When an own property is missing, lookup follows the prototype chain until it finds the property or reaches null.',
`user.hasOwnProperty("name")`,
`Object.hasOwn(user,"name")`,
`const animal={speak(){return"sound"}}; const dog=Object.create(animal); dog.name="Rex"; console.log(dog.name,dog.speak(),Object.getPrototypeOf(dog)===animal);`,
'prototype',R(1,2,2),['Inherited properties can make lookup succeed without object ownership.'],['Distinguish “has property through lookup” from “owns property”.']),

L('constructor-prototype','objects','Constructor functions and shared prototypes',MDN.prototype,
'Constructor functions plus prototypes are the underlying model that class syntax builds on.',
`function User(name){this.name=name;this.greet=function(){return this.name}}`,
`function User(name){this.name=name} User.prototype.greet=function(){return this.name};`,
`function User(name){this.name=name} User.prototype.greet=function(){return"Hi "+this.name}; const a=new User("Ada"),b=new User("Lin"); console.log(a.greet(),a.greet===b.greet);`,
'prototype',R(1,2,2),['Defining methods inside each constructor call allocates separate function objects.'],['Understand prototypes even if you usually write class syntax.']),

L('classes','objects','Class syntax',MDN.classes,
'Classes provide syntax for constructors, prototype methods, inheritance, fields and private elements.',
`function Point(x,y){this.x=x;this.y=y} Point.prototype.length=function(){return Math.hypot(this.x,this.y)};`,
`class Point{constructor(x,y){this.x=x;this.y=y} length(){return Math.hypot(this.x,this.y)}}`,
`class Point{constructor(x,y){this.x=x;this.y=y} length(){return Math.hypot(this.x,this.y)}} console.log(new Point(3,4).length());`,
'prototype',R(1,2,2),['Class methods live on the prototype.'],['Use a class when identity, invariants and shared behavior form a coherent abstraction.']),

L('private-fields','objects','Public and private class fields',MDN.classes,
'Class fields are per-instance state. #private elements are enforced by the language and are not ordinary string properties.',
`class Wallet{balance=0} // callers can set impossible states`,
`class Wallet{#balance=0;deposit(n){if(n>0)this.#balance+=n}get balance(){return this.#balance}}`,
`class Counter{#count=0;increment(){this.#count++}get value(){return this.#count}} const counter=new Counter(); counter.increment(); console.log(counter.value,counter["#count"]);`,
'object',R(1,2,2),['#private names cannot be accessed using bracket-string lookup.'],['Use private state when callers should interact through behavior/invariants.']),

L('inheritance','objects','extends and super',MDN.classes,
'extends creates a derived class; super initializes/accesses base-class behavior.',
`class Admin extends User{constructor(name){this.name=name}}`,
`class Admin extends User{constructor(name){super(name)}}`,
`class User{constructor(name){this.name=name}describe(){return this.name}} class Admin extends User{describe(){return"Admin: "+super.describe()}} console.log(new Admin("Ada").describe());`,
'prototype',R(1,2,3),['Derived constructors must call super before using this.'],['Prefer inheritance only for true substitutable relationships.']),

L('static','objects','Static class members',MDN.classes,
'Static methods/fields belong to the class constructor rather than each instance.',
`const user=new User(); user.parse(raw);`,
`const user=User.parse(raw);`,
`class Temperature{static freezingC=0;static fromFahrenheit(f){return(f-32)*5/9}} console.log(Temperature.freezingC,Temperature.fromFahrenheit(68));`,
'object',R(1,1,2),['Instances do not receive static methods as instance methods.'],['Use static members for behavior about the class/domain that needs no instance.']),

L('getters-setters','objects','Getters and setters',MDN.objects,
'Accessor properties run functions when read or assigned.',
`get profile(){return expensiveRemoteCall()}`,
`get fullName(){return this.first+" "+this.last}`,
`const user={first:"Ada",last:"Lovelace",get fullName(){return this.first+" "+this.last},set fullName(value){[this.first,this.last]=value.split(" ")}}; console.log(user.fullName); user.fullName="Grace Hopper"; console.log(user);`,
'object',R(1,2,2),['Property syntax suggests ordinary access; hiding asynchronous/expensive work behind it is misleading.'],['Use accessors for derived/validated property semantics.']),

L('arrays','collections','Arrays and indexed collections',MDN.arrays,
'Arrays are indexed objects with length and rich sequence methods.',
`const values=new Array(3); values[5]="x";`,
`const values=["a","b","c"];`,
`const values=["a","b","c"]; values.push("d"); console.log(values.length,values[0],values.at(-1),Array.isArray(values));`,
'array',R(1,2,1),['Arrays can be sparse; length is not always populated-element count.'],['Use arrays for ordered sequences.']),

L('array-methods','collections','map, filter, find, some and every',MDN.arrays,
'Array methods encode common sequence questions and transformations.',
`const out=[]; for(const n of values){if(n%2===0)out.push(n*2)}`,
`const out=values.filter(n=>n%2===0).map(n=>n*2);`,
`const values=[1,2,3,4,5]; console.log(values.map(n=>n*n)); console.log(values.filter(n=>n%2===0)); console.log(values.find(n=>n>3)); console.log(values.some(n=>n<0),values.every(n=>n>0));`,
'array',R(2,2,2),['Chaining creates intermediate arrays in common cases.'],['Use the method whose name matches the question you are asking.']),

L('reduce','collections','reduce',MDN.arrays,
'reduce combines a sequence into one accumulated result.',
`const result=values.reduce((acc,item)=>{acc.push(transform(item));return acc},[])`,
`const result=values.map(transform);`,
`const values=[10,20,30]; const total=values.reduce((sum,value)=>sum+value,0); console.log(total);`,
'array',R(2,1,2),['reduce without an initial value throws on an empty array.','It can obscure simpler map/filter operations.'],['Use reduce when “combine into one result” is genuinely the clearest model.']),

L('shallow-copy','collections','Shallow copies and nested identity',MDN.arrays,
'Spread/slice copy the outer array, but nested objects remain shared identities.',
`const copy=[...users]; copy[0].active=false;`,
`const copy=users.map((user,i)=>i===0?{...user,active:false}:user);`,
`const original=[{score:1},{score:2}]; const copy=[...original]; copy[0].score=99; console.log(original[0].score,copy[0]===original[0]);`,
'reference',R(1,3,1),['Shallow copy does not recursively duplicate nested objects.'],['Choose the depth at which identity should be shared.']),

L('map','collections','Map',MDN.keyed,
'Map stores key/value pairs, supports arbitrary key values and preserves insertion order.',
`const dictionary={}; dictionary[objectKey]=value;`,
`const dictionary=new Map(); dictionary.set(objectKey,value);`,
`const key={id:1}; const map=new Map(); map.set(key,"value"); map.set("role","admin"); console.log(map.get(key),map.size); for(const [k,v] of map)console.log(k,v);`,
'map',R(1,2,1),['Object property keys are strings/symbols; Map can key by object identity.'],['Use Map when dynamic keyed data and non-string keys are central.']),

L('set','collections','Set',MDN.keyed,
'Set stores unique values using SameValueZero semantics.',
`const unique=[]; for(const value of values){if(!unique.includes(value))unique.push(value)}`,
`const unique=[...new Set(values)];`,
`const set=new Set([1,2,2,3,NaN,NaN]); console.log([...set],set.has(2),set.size);`,
'set',R(1,2,1),['Objects are unique by identity, not deep equality.'],['Use Set when membership/uniqueness is the primary operation.']),

L('weak-collections','collections','WeakMap and WeakSet',MDN.keyed,
'Weak collections hold object/symbol keys weakly so they do not keep those keys alive solely because of collection membership.',
`const metadata=new Map(); metadata.set(node,info);`,
`const metadata=new WeakMap(); metadata.set(node,info);`,
`const metadata=new WeakMap(); let key={}; metadata.set(key,{seen:true}); console.log(metadata.get(key)); key=null; console.log("binding cleared");`,
'memory',R(1,2,1),['Weak collections are intentionally not enumerable.'],['Use them for metadata tied to another object’s lifetime.']),

L('dates','collections','Date',MDN.dates,
'Date represents one time value in milliseconds since the epoch and offers local/UTC component APIs.',
`const date=new Date(2026,9,1); // zero-based month`,
`const date=new Date("2026-10-01T00:00:00Z");`,
`const now=new Date(); console.log(now.toISOString()); console.log(new Date(0).toISOString());`,
'values',R(1,1,1),['Some constructors/methods use local-time semantics.'],['Use ISO strings to make offset intent visible and Intl for human formatting.']),

L('regexp','collections','Regular expressions',MDN.regex,
'Regular expressions describe text patterns for matching, searching and replacement.',
`const parts=text.split(" ").filter(x=>x.includes("@"));`,
`const emails=text.match(/\\b[^\\s@]+@[^\\s@]+\\.[^\\s@]+\\b/g)??[];`,
`const input="Order AB-123 and XY-9"; const re=/([A-Z]{2})-(\\d+)/g; for(const match of input.matchAll(re))console.log(match[0],match[1],match[2]);`,
'regex',R(2,1,2),['Dense regexes can become maintenance hazards.'],['Keep pattern purpose visible in surrounding names/tests.'])
];
