export const NODE = {
  docs:'https://nodejs.org/api/',
  globals:'https://nodejs.org/api/globals.html',
  process:'https://nodejs.org/api/process.html',
  modules:'https://nodejs.org/api/modules.html',
  esm:'https://nodejs.org/api/esm.html',
  packages:'https://nodejs.org/api/packages.html',
  events:'https://nodejs.org/api/events.html',
  timers:'https://nodejs.org/api/timers.html',
  fs:'https://nodejs.org/api/fs.html',
  http:'https://nodejs.org/api/http.html',
  buffer:'https://nodejs.org/api/buffer.html',
  stream:'https://nodejs.org/api/stream.html',
  webstreams:'https://nodejs.org/api/webstreams.html',
  workers:'https://nodejs.org/api/worker_threads.html',
  child:'https://nodejs.org/api/child_process.html',
  perf:'https://nodejs.org/api/perf_hooks.html',
  v8:'https://nodejs.org/api/v8.html',
  asyncContext:'https://nodejs.org/api/async_context.html',
  errors:'https://nodejs.org/api/errors.html',
  os:'https://nodejs.org/api/os.html',
  path:'https://nodejs.org/api/path.html',
  url:'https://nodejs.org/api/url.html',
  crypto:'https://nodejs.org/api/crypto.html',
  learnLoop:'https://nodejs.org/en/learn/asynchronous-work/event-loop-timers-and-nexttick',
  dontBlock:'https://nodejs.org/en/learn/asynchronous-work/dont-block-the-event-loop'
};

const R=(cpu=0,heap=0,stack=0,queue=0,dom=0,network=0,native=0,threads=0)=>({cpu,heap,stack,queue,dom,network,native,threads});
const L=(id,title,source,summary,bad,good,code,visual,resources,traps=[],tips=[])=>({id,topic:'node',title,source,summary,compare:{bad,good},code,visual,resources,traps,tips,runner:'node-model'});

export const NODE_TOPICS=[
  {id:'node',title:'Node.js runtime & OS resources',description:'The Node host, event loop, I/O, buffers, streams, workers, memory and observability.'}
];

export const NODE_LESSONS=[
L('node-host','Node.js is a JavaScript host',NODE.docs,
'Node runs the same ECMAScript language in a server-oriented host that supplies process, file-system, networking and other runtime APIs.',
`// treating browser and Node as different JavaScript languages`,
`// same language semantics; different host APIs and globals`,
`console.log("Portable JavaScript still uses Array, Map, Promise, classes, closures and modules.");`,
'node-host',R(1,1,1),['Browser globals such as document are not part of core JavaScript.','Node-specific APIs are host capabilities.'],['Separate portable domain logic from host adapters.']),

L('node-globals','Node globals and globalThis',NODE.globals,
'Node exposes a set of host-provided globals in addition to ECMAScript built-ins. globalThis is the cross-environment global reference, but its properties are host-specific.',
`// assume every browser global exists on the server`,
`if (typeof document === "undefined") { /* not a browser DOM */ }`,
`console.log("In Node, inspect globalThis plus documented Node globals rather than assuming window/document.");`,
'node-host',R(1,1,1),['A name being global does not make it part of ECMAScript.'],['Gate host-specific code explicitly.']),

L('node-esm-commonjs','ES modules and CommonJS',NODE.esm,
'Node supports ECMAScript modules and CommonJS. Their loading, file naming, package metadata and interop rules differ.',
`const helper=require("./helper"); // mixed casually with import/export`,
`import {helper} from "./helper.js"; // choose one module contract deliberately`,
`console.log("This browser lab cannot execute Node module resolution; inspect the source/visual model and run the equivalent in Node locally.");`,
'node-module',R(1,2,1,1),['Module system choice affects resolution, package metadata and interop.'],['Prefer one clear module strategy within a package unless interop is required.']),

L('node-packages','Packages, exports and resolution',NODE.packages,
'Node package metadata controls package type, entry points and which internal paths consumers may import.',
`// consumers import deep internal files by accident`,
`// expose deliberate public entry points through package metadata`,
`console.log("Package boundaries are runtime/module-resolution contracts, not only folder organization.");`,
'node-module',R(1,1,1,1),['Changing package exports can be a breaking API change.'],['Treat the package public surface as an API.']),

L('node-event-loop','Node event loop',NODE.learnLoop,
'Node coordinates JavaScript callbacks around an event loop while delegating many operations to the operating system or libuv facilities.',
`while (expensiveWork()) {} // blocks progress for every request on this event loop`,
`await asyncIO(); // event loop can run other ready work while I/O is pending`,
`console.log("Visualize: JS callback → host/libuv/OS → completion becomes ready → JS callback resumes.");`,
'node-event-loop',R(2,2,1,3,0,2,2,1),['Asynchronous I/O does not mean JavaScript callbacks execute simultaneously on one event-loop thread.'],['Keep each callback/job bounded.']),

L('node-dont-block','Do not block the event loop',NODE.dontBlock,
'Long CPU-heavy JavaScript callbacks reduce throughput and increase latency because other clients wait for the event-loop thread to become available.',
`server.on("request",()=>{ expensiveCpuLoop(); respond(); });`,
`server.on("request",()=>{ queueCpuWork(); respondWhenReady(); });`,
`console.log("Stress the visualization to see one long callback delay many unrelated requests.");`,
'node-event-loop',R(3,2,2,3,0,1,1,1),['Async/await does not make CPU-heavy code non-blocking.'],['Partition work, use workers for CPU-heavy JS, or move computation to an appropriate service/runtime.']),

L('node-timers','Timers and setImmediate',NODE.timers,
'Node timer APIs schedule callbacks for future event-loop processing; a delay is a threshold, not an exact execution time.',
`setTimeout(work,0); // assume exact immediate execution`,
`setTimeout(work,0); // treat as “eligible no earlier than this delay”`,
`console.log("Node timer ordering also depends on event-loop phase and other ready work.");`,
'node-event-loop',R(1,1,1,2),['Timer delay is not a real-time guarantee.'],['Avoid correctness assumptions based on exact callback timing.']),

L('node-events','EventEmitter',NODE.events,
'EventEmitter is a Node host abstraction for synchronous listener invocation when an event is emitted.',
`emitter.on("data",heavyListener); // many heavy listeners on a hot event`,
`emitter.on("data",smallListener); // keep listener work bounded/delegate expensive work`,
`console.log("EventEmitter listeners run when emit() is called; their synchronous work contributes directly to callback duration.");`,
'node-event',R(2,2,2,1),['EventEmitter is not a background thread or queue by itself.','Listener leaks can retain objects and trigger warnings.'],['Remove listeners when their lifecycle ends.']),

L('node-fs-sync-async','Synchronous vs asynchronous file system APIs',NODE.fs,
'Node file-system APIs often offer synchronous and asynchronous forms. Synchronous operations block the event-loop thread until completion.',
`const text=readFileSync(path,"utf8"); // inside a request path`,
`const text=await fs.promises.readFile(path,"utf8");`,
`console.log("Visualize sync: JS thread waits. Async: host starts I/O and JS can process other ready callbacks.");`,
'node-fs',R(1,2,1,2,0,1,3,2),['Synchronous I/O can be acceptable in startup/CLI contexts but is hazardous on shared request paths.'],['Choose based on whether blocking this process thread is acceptable.']),

L('node-buffer','Buffer and external/native memory',NODE.buffer,
'Buffer is a Node subclass of Uint8Array used for fixed-length bytes. Buffer memory contributes to process memory differently from ordinary JavaScript objects.',
`const data=[]; for(const byte of bytes)data.push(byte);`,
`const data=Buffer.from(bytes);`,
`console.log("Node Buffer uses byte-oriented memory and interoperates with Uint8Array/ArrayBuffer semantics.");`,
'node-buffer',R(1,1,1,0,0,0,3),['Large Buffers can increase external/ArrayBuffer memory even when JS heap metrics look stable.'],['Monitor process memory fields, not heapUsed alone.']),

L('node-buffer-unsafe','Buffer allocation safety',NODE.buffer,
'Buffer.alloc initializes memory; Buffer.allocUnsafe may reuse uninitialized memory and exists for performance-sensitive cases where the bytes will be fully overwritten.',
`const buf=Buffer.allocUnsafe(size); send(buf); // bytes not fully initialized`,
`const buf=Buffer.alloc(size); // initialized`,
`console.log("Never expose uninitialized bytes; choose allocUnsafe only with a proven full overwrite path.");`,
'node-buffer',R(1,1,1,0,0,0,3),['Uninitialized memory can contain sensitive prior data if read before overwrite.'],['Prefer Buffer.alloc unless the performance trade-off is measured and the overwrite invariant is guaranteed.']),

L('node-streams','Streams and incremental data',NODE.stream,
'Node streams process data incrementally instead of materializing entire payloads in memory.',
`const all=await readEntireHugeFile(); await send(all);`,
`createReadStream(path).pipe(response);`,
`console.log("Visualize chunks moving through a bounded pipeline instead of one giant heap allocation.");`,
'node-stream',R(1,2,1,2,0,2,2),['Streaming changes error/cancellation handling and lifetime management.'],['Prefer streaming for large or continuous data when consumers can process chunks.']),

L('node-backpressure','Stream backpressure and highWaterMark',NODE.stream,
'Backpressure prevents a fast producer from indefinitely outrunning a slower consumer. Internal queue thresholds such as highWaterMark help control buffering.',
`source.on("data",chunk=>destination.write(chunk)); // ignore write() pressure`,
`if(!destination.write(chunk)) source.pause(); destination.once("drain",()=>source.resume());`,
`console.log("Stress the visualizer to see queue memory rise when producer rate exceeds consumer rate.");`,
'node-stream',R(2,3,1,3,0,2,2),['Ignoring backpressure can turn throughput mismatch into unbounded memory growth.'],['Treat queue size as a resource budget.']),

L('node-http','HTTP server lifecycle',NODE.http,
'Node HTTP servers expose request/response streams. Per-request synchronous CPU work and unbounded buffering directly affect server latency and memory.',
`server.on("request",async(req,res)=>{ const body=await readAll(req); expensiveCpu(body); res.end("ok"); });`,
`server.on("request",(req,res)=>{ streamOrBound(req); keepCpuWorkBounded(); });`,
`console.log("Conceptual path: socket → parser → JS request callback → response writes → socket.");`,
'node-http',R(2,2,2,2,0,3,2),['Request/response objects are streams.','One slow callback can delay unrelated requests on the same event loop.'],['Bound body sizes and synchronous work.']),

L('node-workers','Worker threads for CPU-intensive JavaScript',NODE.workers,
'worker_threads runs JavaScript in parallel threads. Node documentation recommends workers for CPU-intensive JavaScript, not ordinary asynchronous I/O.',
`await Promise.all(items.map(expensiveCpu)); // still CPU work on main JS thread`,
`send CPU jobs to a reusable worker pool; keep I/O on normal async APIs`,
`console.log("Worker threads can run JS in parallel and can transfer/share ArrayBuffer data.");`,
'node-worker',R(3,3,1,1,0,0,2,3),['Spawning a fresh worker per tiny task can cost more than the work.','Shared memory introduces synchronization complexity.'],['Use a worker pool for repeated CPU tasks.']),

L('node-child-process','Child processes',NODE.child,
'child_process starts separate OS processes, giving stronger process isolation and allowing execution of other programs at the cost of IPC/process overhead.',
`exec(userInput); // shell command built from untrusted data`,
`spawn(executable,args,{shell:false}); // validate executable/arguments`,
`console.log("Process model: parent Node process ↔ OS child process via pipes/IPC.");`,
'node-process',R(1,1,1,1,0,1,3,3),['Shell invocation with untrusted input can become command injection.'],['Use explicit executables/arguments and validate external command boundaries.']),

L('node-memory-usage','process.memoryUsage()',NODE.process,
'process.memoryUsage() reports rss, heapTotal, heapUsed, external and arrayBuffers. RSS represents resident process memory; heap metrics describe V8-managed heap portions.',
`if(heapUsedLooksFine) assumeMemoryIsFine();`,
`inspect rss, heapUsed, external and arrayBuffers together, then correlate with workload`,
`console.log("In Node: process.memoryUsage() separates V8 heap from external/ArrayBuffer memory and process RSS.");`,
'node-memory',R(1,3,1,0,0,0,3),['RSS can grow even when heapUsed is stable.','Buffers/ArrayBuffers contribute to external/native memory.'],['Graph memory fields over time and correlate growth with request/workload patterns.']),

L('node-v8-heap','V8 heap statistics',NODE.v8,
'Node exposes V8 heap statistics and heap-space information for deeper runtime diagnostics.',
`// only look at one heapUsed number`,
`// use V8/process metrics together when diagnosing heap limits or space behavior`,
`console.log("V8 heap diagnostics expose engine-specific heap statistics; treat them as runtime diagnostics rather than application state.");`,
'node-memory',R(1,3,1,0,0,0,2),['V8-specific metrics can change with engine/runtime versions.'],['Use them to investigate, not to couple business logic to heap internals.']),

L('node-event-loop-util','Event-loop utilization and delay',NODE.perf,
'perf_hooks exposes event-loop utilization and delay monitoring, helping separate an overloaded/busy event loop from other bottlenecks.',
`// infer event-loop health only from request latency`,
`// measure ELU/event-loop delay alongside request latency and CPU`,
`console.log("In Node, eventLoopUtilization measures event-loop active vs idle time; monitorEventLoopDelay tracks delay distribution.");`,
'node-performance',R(2,1,1,3,0,0,1,1),['ELU is not the same as whole-process CPU utilization.'],['Correlate ELU/delay with CPU, latency and workload rather than interpreting one metric alone.']),

L('node-async-local-storage','AsyncLocalStorage and request context',NODE.asyncContext,
'AsyncLocalStorage carries contextual state through asynchronous call chains without manually threading it through every function parameter.',
`global.currentRequestId=id; // concurrent requests overwrite each other`,
`storage.run({requestId:id},()=>handleRequest());`,
`console.log("Async context is useful for tracing/request metadata; it is not a substitute for explicit domain data flow.");`,
'node-context',R(1,2,1,2),['Global mutable context breaks under concurrent requests.'],['Keep async context small and operational, such as trace/request identifiers.']),

L('node-errors','Operational error boundaries',NODE.errors,
'Node APIs surface errors through synchronous throws, rejected promises, callbacks and emitted error events depending on the API.',
`try { await task(); } catch(e) { /* ignore */ }`,
`try { await task(); } catch(error) { addContext(error); throw error; }`,
`console.log("Know the error channel of the specific Node API: throw, rejection, callback, or EventEmitter error.");`,
'node-error',R(1,1,2,1),['An unhandled EventEmitter error event can terminate the process.'],['Preserve causes/context and define process-level fatal-error policy deliberately.']),

L('node-os-resources','OS resources: threads, sockets, descriptors and memory',NODE.os,
'Node applications ultimately consume operating-system resources: resident memory, CPU time, threads, sockets and file descriptors. JavaScript abstractions do not remove those limits.',
`// assume “async” means free/unlimited resources`,
`// bound concurrency, buffers, sockets and worker counts to resource budgets`,
`console.log("The resource visualizer maps JavaScript choices down to conceptual OS pressure: CPU, RSS/native memory, threads and sockets.");`,
'node-os',R(2,2,1,2,0,2,3,3),['Async concurrency can exhaust sockets/descriptors/memory even without blocking the event loop.'],['Set explicit concurrency/resource limits and observe actual production resource metrics.'])
];