export const MDN_RUNTIME = {
  promises:'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Using_promises',
  typed:'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Typed_arrays',
  iterators:'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Iterators_and_generators',
  resources:'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Resource_management',
  intl:'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Internationalization',
  modules:'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules',
  meta:'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Meta_programming',
  memory:'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Memory_management',
  execution:'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Execution_model',
  microtasks:'https://developer.mozilla.org/en-US/docs/Web/API/HTML_DOM_API/Microtask_guide/In_depth',
  globalThis:'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/globalThis',
  dom:'https://developer.mozilla.org/en-US/docs/Web/API/Document_Object_Model',
  events:'https://developer.mozilla.org/en-US/docs/Learn_web_development/Core/Scripting/Events',
  fetch:'https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch',
  workers:'https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Using_web_workers',
  storage:'https://developer.mozilla.org/en-US/docs/Web/API/Web_Storage_API',
  websocket:'https://developer.mozilla.org/en-US/docs/Web/API/WebSocket',
  performance:'https://developer.mozilla.org/en-US/docs/Web/API/Performance',
  observer:'https://developer.mozilla.org/en-US/docs/Web/API/PerformanceObserver',
  raf:'https://developer.mozilla.org/en-US/docs/Web/API/Window/requestAnimationFrame',
  structuredClone:'https://developer.mozilla.org/en-US/docs/Web/API/Window/structuredClone'
};

const R=(cpu=0,heap=0,stack=0,queue=0,dom=0,network=0,native=0,threads=0)=>({cpu,heap,stack,queue,dom,network,native,threads});
const L=(id,topic,title,source,summary,bad,good,code,visual,resources,traps=[],tips=[],runner='worker')=>({id,topic,title,source,summary,compare:{bad,good},code,visual,resources,traps,tips,runner});

export const RUNTIME_TOPICS=[
  {id:'iteration',title:'Iterators & generators',description:'Iteration protocols, generators and lazy work.'},
  {id:'async',title:'Promises & execution model',description:'Promises, async/await, call stack, tasks, microtasks and agents.'},
  {id:'modules',title:'Modules & resources',description:'ES modules, dynamic loading and deterministic resource cleanup.'},
  {id:'advanced',title:'Memory & metaprogramming',description:'Garbage collection, Proxy, Reflect, globalThis and advanced runtime mechanics.'},
  {id:'browser',title:'JavaScript in the browser',description:'DOM, events, rendering, fetch, workers, storage and WebSocket.'}
];

export const RUNTIME_LESSONS=[
L('iterator-protocol','iteration','The iterator protocol',MDN_RUNTIME.iterators,
'An iterator has next() returning {value, done}; an iterable exposes an iterator via Symbol.iterator. for...of, spread and destructuring build on these protocols.',
`let index=0; while(index<values.length) console.log(values[index++]);`,
`for(const value of values) console.log(value);`,
`const iterator=["a","b"][Symbol.iterator](); console.log(iterator.next()); console.log(iterator.next()); console.log(iterator.next());`,
'iteration',R(1,1,1),['Iterator and iterable are related but distinct protocols.'],['Understand the protocol to reason about for...of, spread and generators.']),

L('custom-iterable','iteration','Creating a custom iterable',MDN_RUNTIME.iterators,
'Any object can become iterable by implementing Symbol.iterator and returning an iterator.',
`const range={start:1,end:3}; // every consumer must know the shape`,
`const range={*[Symbol.iterator](){yield 1;yield 2;yield 3;}};`,
`const range={start:3,end:6,*[Symbol.iterator](){for(let n=this.start;n<=this.end;n++)yield n;}}; console.log([...range]);`,
'iteration',R(1,1,2),['Custom iteration should have unsurprising order and termination.'],['Making a domain sequence iterable lets it compose with built-in syntax.']),

L('generators','iteration','Generator functions and yield',MDN_RUNTIME.iterators,
'Generator functions can pause at yield and resume on later next() calls while preserving execution state.',
`function makeRange(n){return Array.from({length:n},(_,i)=>i);}`,
`function* range(n){for(let i=0;i<n;i++)yield i;}`,
`function* range(start,end){for(let n=start;n<=end;n++)yield n;} const it=range(2,4); console.log(it.next()); console.log(it.next()); console.log([...it]);`,
'generator',R(1,1,2),['Calling a generator function returns a generator immediately; the body advances as consumed.'],['Use generators for lazy/stateful iteration when materializing everything is unnecessary.']),

L('yield-delegation','iteration','yield* delegation',MDN_RUNTIME.iterators,
'yield* delegates iteration to another iterable and makes generators composable.',
`for(const x of first)yield x; for(const x of second)yield x;`,
`yield* first; yield* second;`,
`function* combined(){yield "start"; yield* [1,2,3]; yield "end";} console.log([...combined()]);`,
'generator',R(1,1,2),['yield* delegates; it does not yield the iterable object as one value.'],['Use delegation to compose generator pipelines.']),

L('lazy-iteration','iteration','Lazy iteration',MDN_RUNTIME.iterators,
'Iterators can produce values only when requested, reducing peak memory and avoiding work if the consumer stops early.',
`const million=Array.from({length:1_000_000},(_,i)=>i);`,
`function* numbers(limit){for(let i=0;i<limit;i++)yield i;}`,
`function* squares(limit){for(let n=0;n<limit;n++){console.log("compute",n);yield n*n;}} const seq=squares(5); console.log(seq.next().value); console.log(seq.next().value);`,
'generator',R(1,1,2),['Laziness changes when side effects and errors occur.'],['Use lazy sequences when data is large or consumers may stop early.']),

L('promise-basics','async','Promise states and chaining',MDN_RUNTIME.promises,
'A Promise represents eventual completion or failure. then() returns a new promise, allowing transformations and error propagation to form a chain.',
`load().then(value=>{process(value).then(result=>console.log(result));});`,
`load().then(process).then(console.log).catch(console.error);`,
`Promise.resolve(3).then(v=>v*2).then(v=>{console.log("result",v);return v+1;}).then(console.log);`,
'promise',R(1,2,1,2),['Forgetting to return a promise/value inside then can break the intended chain.'],['Return promises rather than nesting then calls.']),

L('promise-errors','async','Promise rejection and error propagation',MDN_RUNTIME.promises,
'Thrown errors and rejected promises propagate down a chain until a rejection handler catches them.',
`doA().then(doB,handleAError);`,
`doA().then(doB).catch(handleError);`,
`Promise.resolve("start").then(()=>{throw new Error("boom")}).then(()=>console.log("skipped")).catch(e=>console.log("caught",e.message));`,
'promise',R(1,1,1,2),['The second argument to then handles rejection from the previous promise, not errors thrown by the success handler.'],['A final catch often creates the clearest chain error boundary.']),

L('async-await','async','async functions and await',MDN_RUNTIME.promises,
'async functions return promises. await suspends that async function until a promise settles; it does not block the whole JavaScript agent.',
`async function load(){return fetchData().then(parse).then(transform);}`,
`async function load(){const data=await fetchData();const parsed=await parse(data);return transform(parsed);}`,
`const wait=ms=>new Promise(r=>setTimeout(r,ms)); async function demo(){console.log("before");await wait(20);console.log("after");return 42;} console.log(await demo());`,
'event-loop',R(1,2,1,2),['await pauses only the current async function.'],['Use await for dependency order; avoid serializing independent operations accidentally.']),

L('promise-combinators','async','Promise.all, allSettled, any and race',MDN_RUNTIME.promises,
'Promise combinators encode different concurrency and failure semantics for groups of promises.',
`const a=await loadA(); const b=await loadB();`,
`const [a,b]=await Promise.all([loadA(),loadB()]);`,
`const delay=(x,ms)=>new Promise(r=>setTimeout(()=>r(x),ms)); console.log(await Promise.all([delay("a",30),delay("b",10)])); console.log(await Promise.race([delay("slow",30),delay("fast",5)]));`,
'event-loop',R(1,2,1,3),['Promise.all rejects on first rejection; allSettled waits for every outcome.'],['Pick a combinator based on failure semantics, not only speed.']),

L('engine-host','async','JavaScript engine vs host environment',MDN_RUNTIME.execution,
'The engine implements ECMAScript. The host supplies external capabilities. Browsers and Node.js are different hosts around the same core language.',
`// “JavaScript itself provides document and file-system APIs”`,
`// Core: Array, Map, Promise, classes. Host: DOM or server-specific APIs.`,
`console.log(typeof Array,typeof Promise,typeof globalThis); console.log("worker document",typeof document); console.log("worker window",typeof window);`,
'host',R(1,1,1),['Language semantics and host APIs are separate layers.'],['When behavior differs by environment, ask “language difference or host difference?”']),

L('call-stack','async','Execution contexts and the call stack',MDN_RUNTIME.execution,
'Calling a function pushes an execution context; returning removes it. The top stack frame is the currently executing JavaScript in an agent.',
`function a(){b()} function b(){c()} function c(){throw new Error("boom")}`,
`// Read a synchronous stack from the current frame outward.`,
`function first(){second()} function second(){third()} function third(){console.trace("stack")} first();`,
'stack',R(1,1,3),['The call stack is not the task or microtask queue.'],['For synchronous errors, walk frames from the throw site outward.']),

L('event-loop','async','Jobs, event loop and run-to-completion',MDN_RUNTIME.execution,
'JavaScript jobs run to completion. Host-scheduled callbacks wait until current JavaScript finishes.',
`console.log("A"); setTimeout(()=>console.log("B"),0); console.log("C"); // expecting A B C`,
`// Current job finishes before the timer callback can execute.`,
`console.log("A"); setTimeout(()=>console.log("timer"),0); console.log("B");`,
'event-loop',R(1,1,1,3),['A zero-delay timer does not mean immediate execution.'],['Separate “scheduled now” from “executes now”.']),

L('microtasks','async','Tasks vs microtasks',MDN_RUNTIME.microtasks,
'After a task finishes, queued microtasks are drained before the host proceeds to the next task and, in browsers, rendering opportunities.',
`setTimeout(()=>console.log("timer"),0); Promise.resolve().then(()=>console.log("promise")); // expecting timer first`,
`// Promise reactions/queueMicrotask run before the next timer task.`,
`console.log("sync"); setTimeout(()=>console.log("task"),0); queueMicrotask(()=>console.log("microtask")); Promise.resolve().then(()=>console.log("promise reaction")); console.log("sync end");`,
'event-loop',R(1,1,1,3),['A self-replenishing microtask queue can starve later tasks/rendering.'],['Know which queue an API uses before reasoning about ordering.']),

L('run-to-completion','async','Long jobs and responsiveness',MDN_RUNTIME.execution,
'A running job is not preempted by another job in the same agent. Long synchronous work delays queued callbacks and browser responsiveness.',
`for(let i=0;i<5_000_000_000;i++) {}`,
`// Split work, yield between chunks, or move suitable CPU work to a Worker.`,
`const start=performance.now(); let sum=0; for(let i=0;i<1_000_000;i++)sum+=i; console.log("ms",Math.round(performance.now()-start),"sum",sum);`,
'event-loop',R(3,1,1,3,2),['async syntax does not automatically move CPU work to another thread.'],['Keep browser main-thread jobs short enough to preserve responsiveness.']),

L('realms','async','Realms, globals and cross-realm values',MDN_RUNTIME.execution,
'Different realms have distinct global objects and intrinsic objects. Windows/iframes/workers can therefore have separate constructors and globals.',
`value instanceof Array // assumed universal across realms`,
`Array.isArray(value)`,
`const value=[]; console.log(Array.isArray(value),value instanceof Array,globalThis===self);`,
'host',R(1,1,1),['Cross-realm instanceof can surprise because constructors belong to different realms.'],['Prefer brand-checking APIs such as Array.isArray for cross-realm values.']),

L('es-modules','modules','ES modules: import and export',MDN_RUNTIME.modules,
'Modules provide explicit file-level dependency boundaries. Imports and exports are statically analyzable in their declarative form.',
`// several classic scripts communicate through implicit globals`,
`export function add(a,b){return a+b} // import {add} from "./math.js"`,
`const src='export const value=42; export default x=>x*2;'; const url=URL.createObjectURL(new Blob([src],{type:"text/javascript"})); const mod=await import(url); console.log(mod.value,mod.default(5)); URL.revokeObjectURL(url);`,
'module',R(1,2,1,2),['Modules are strict mode.','Resolution/loading details depend on the host.'],['Export a deliberate public surface instead of relying on globals.']),

L('named-default','modules','Named and default exports',MDN_RUNTIME.modules,
'Named exports preserve explicit exported names; one default export can be imported under a local name chosen by the importer.',
`export default {parse,format,validate};`,
`export {parse,format,validate};`,
`const src='export const a=1; export const b=2; export default 3;'; const url=URL.createObjectURL(new Blob([src],{type:"text/javascript"})); const mod=await import(url); console.log(mod.a,mod.b,mod.default); URL.revokeObjectURL(url);`,
'module',R(1,2,1,2),['Default import names can vary across import sites.'],['Choose the style that makes the module API easiest to discover/refactor.']),

L('dynamic-import','modules','Dynamic import()',MDN_RUNTIME.modules,
'import() loads a module asynchronously and resolves to its module namespace, allowing conditional or deferred loading.',
`// eagerly load every optional feature on startup`,
`const feature=await import("./feature.js");`,
`const src='export const loadedAt=Date.now();'; const url=URL.createObjectURL(new Blob([src],{type:"text/javascript"})); console.log("before"); const mod=await import(url); console.log("after",mod.loadedAt); URL.revokeObjectURL(url);`,
'module',R(1,2,1,2,0,1),['Dynamic import changes timing and error handling.'],['Use it when a dependency is conditional or can be deferred.']),

L('live-bindings','modules','Module exports are live bindings',MDN_RUNTIME.modules,
'Imported bindings reflect updates made by the exporting module instead of being one-time copied values.',
`// think of import as copying a value once`,
`// imported names remain bindings to exported module state`,
`const src='export let count=0; export function inc(){count++}'; const url=URL.createObjectURL(new Blob([src],{type:"text/javascript"})); const mod=await import(url); console.log(mod.count); mod.inc(); console.log(mod.count); URL.revokeObjectURL(url);`,
'module',R(1,2,1),['Importers cannot normally assign directly to an imported binding.'],['Treat exported mutable bindings as shared module state and use them sparingly.']),

L('resource-management','modules','Explicit resource management',MDN_RUNTIME.resources,
'using/await using and disposable protocols provide deterministic cleanup for resources whose lifetime should not depend on garbage collection.',
`const resource=acquire(); try {use(resource)} finally {resource.close()}`,
`// where supported: using resource=acquire();`,
`console.log("Symbol.dispose",typeof Symbol.dispose); console.log("Symbol.asyncDispose",typeof Symbol.asyncDispose);`,
'resource',R(1,1,1),['Engine support for using syntax may vary.','Garbage collection is not deterministic external-resource cleanup.'],['Separate memory reachability from release of files, locks, sockets and similar resources.']),

L('typed-arrays','advanced','Typed arrays',MDN_RUNTIME.typed,
'Typed arrays are array-like views for reading/writing raw binary data in fixed numeric formats.',
`const bytes=[255,0,128];`,
`const bytes=new Uint8Array([255,0,128]);`,
`const bytes=new Uint8Array([255,256,-1,128]); console.log([...bytes]); console.log(bytes.byteLength,Array.isArray(bytes));`,
'binary',R(1,1,1,0,0,0,2),['Values are converted to the target representation.','Typed arrays are not normal resizable arrays.'],['Use typed arrays for binary data/layout, not as a default Array replacement.']),

L('arraybuffer-dataview','advanced','ArrayBuffer and DataView',MDN_RUNTIME.typed,
'ArrayBuffer stores bytes; typed arrays/DataView interpret those bytes using chosen numeric types and byte order.',
`const packet=[0,1,255,2]; // layout implicit`,
`const buffer=new ArrayBuffer(4); const view=new DataView(buffer); view.setUint16(0,513);`,
`const buffer=new ArrayBuffer(4); const view=new DataView(buffer); view.setUint16(0,0x1234,false); console.log(new Uint8Array(buffer));`,
'binary',R(1,1,1,0,0,0,2),['Byte order matters for multi-byte values.'],['Separate “these bytes exist” from “these bytes represent this numeric layout”.']),

L('memory-lifecycle','advanced','Memory lifecycle and garbage collection',MDN_RUNTIME.memory,
'JavaScript allocates memory for values/objects and automatically reclaims memory that becomes unreachable. Developers still control reachability through references.',
`cache.push(hugeObject); // never evicted`,
`cache.delete(key); // remove references when data is no longer needed`,
`let object={data:new Array(1000).fill("x")}; const alias=object; object=null; console.log("still reachable",alias.data.length);`,
'memory',R(1,3,1),['Clearing one binding does not collect an object if another reachable reference remains.'],['Think in reachability graphs, not manual “freeing”.']),

L('closure-memory','advanced','Closures and retained memory',MDN_RUNTIME.memory,
'A long-lived closure keeps captured bindings reachable, which can retain a much larger object graph than the callback itself suggests.',
`function handler(huge){return()=>huge[0]} handlers.push(handler(hugeData));`,
`function handler(firstValue){return()=>firstValue}`,
`function capture(){const large=new Array(1000).fill("data"); return()=>large.length;} const fn=capture(); console.log(fn());`,
'memory',R(1,3,1),['Small callbacks can retain large captured object graphs.'],['Capture only what long-lived callbacks actually need when memory matters.']),

L('proxy','advanced','Proxy',MDN_RUNTIME.meta,
'Proxy intercepts fundamental object/function operations using traps such as get, set, has and apply.',
`// duplicate manual logging around every property access`,
`const observed=new Proxy(target,{get(t,k,r){console.log(k);return Reflect.get(t,k,r)}});`,
`const target={count:1}; const proxy=new Proxy(target,{get(t,k,r){console.log("get",String(k));return Reflect.get(t,k,r)}}); console.log(proxy.count);`,
'proxy',R(2,2,2),['Proxy changes fundamental object semantics and can increase debugging/performance complexity.'],['Use it when interception is the abstraction, not as a default object pattern.']),

L('reflect','advanced','Reflect',MDN_RUNTIME.meta,
'Reflect exposes functions corresponding to many internal object operations and is especially useful for forwarding Proxy behavior correctly.',
`target[key]=value; return true;`,
`return Reflect.set(target,key,value,receiver);`,
`const object={}; console.log(Reflect.set(object,"x",10)); console.log(Reflect.get(object,"x")); console.log(Reflect.ownKeys(object));`,
'proxy',R(1,1,1),['Reflect methods expose operation results explicitly.'],['Inside Proxy traps, Reflect is often the cleanest default forwarding operation.']),

L('global-this','advanced','globalThis',MDN_RUNTIME.globalThis,
'globalThis is the standard global-this reference across host environments; the properties present on it still depend on the host.',
`const root=window; // browser-specific`,
`const root=globalThis;`,
`console.log(typeof globalThis); globalThis.demoValue=42; console.log(globalThis.demoValue); delete globalThis.demoValue;`,
'host',R(1,1,1),['The global object is not the same set of APIs in every host.'],['Use globalThis only when global access is genuinely required.']),

L('intl','advanced','Internationalization with Intl',MDN_RUNTIME.intl,
'Intl provides locale-aware formatting/collation so application code does not hard-code cultural presentation rules.',
`const price=value.toFixed(2)+" EUR";`,
`new Intl.NumberFormat("de-DE",{style:"currency",currency:"EUR"}).format(value);`,
`const value=123456.78; for(const locale of ["en-GB","de-DE","ja-JP"]) console.log(locale,new Intl.NumberFormat(locale,{style:"currency",currency:"GBP"}).format(value));`,
'values',R(1,1,1),['Locale formatting is presentation; do not parse business values back from formatted strings.'],['Keep raw values separate from localized display.']),

L('browser-host','browser','Browser host: JavaScript + Web APIs',MDN_RUNTIME.execution,
'Browser JavaScript combines the ECMAScript language with host APIs such as Window, Document, timers, fetch and events.',
`// assume document is part of the JavaScript language`,
`// engine: language semantics; browser host: DOM/Web APIs`,
`document.body.innerHTML='<main style="font-family:system-ui;padding:1rem"><h2>Hello</h2><p id="status">Browser host DOM</p></main>'; console.log(document.querySelector("#status").textContent);`,
'browser-host',R(1,2,1,1,2),['document/window are browser-host APIs, not core JavaScript.'],['Keep portable core logic separated from browser adapters.'],'dom'),

L('dom-tree','browser','DOM tree and document queries',MDN_RUNTIME.dom,
'The DOM exposes document content as a mutable object tree that JavaScript can query and change.',
`document.body.innerHTML += "<button>Save</button>";`,
`const button=document.createElement("button"); button.textContent="Save"; document.body.append(button);`,
`document.body.innerHTML='<main><h2>Users</h2><ul id="users"></ul></main>'; const list=document.querySelector("#users"); for(const name of ["Ada","Lin","Grace"]){const li=document.createElement("li");li.textContent=name;list.append(li)} console.log("items",list.children.length);`,
'dom',R(1,2,1,1,3),['innerHTML parses markup and is dangerous with untrusted strings.'],['Prefer textContent/createElement for untrusted plain text.'],'dom'),

L('dom-batching','browser','DOM work, style/layout and batching',MDN_RUNTIME.dom,
'Repeated DOM reads/writes can force the browser to repeatedly recalculate style/layout. Grouping work reduces main-thread/rendering pressure.',
`for(const item of items){ el.style.width=(el.offsetWidth+1)+"px"; }`,
`const width=el.offsetWidth; for(const item of items){ /* compute */ } el.style.width=(width+items.length)+"px";`,
`document.body.innerHTML='<div id="box" style="width:100px;height:30px;background:#222"></div>'; const box=document.querySelector("#box"); const before=box.getBoundingClientRect().width; for(let i=0;i<100;i++) box.style.width=(before+i)+"px"; console.log("final width",box.getBoundingClientRect().width);`,
'render-pipeline',R(2,2,1,1,3),['Layout reads after style writes can synchronize browser rendering work.'],['Batch reads together and writes together on hot rendering paths.'],'dom'),

L('browser-events','browser','Browser events and propagation',MDN_RUNTIME.events,
'EventTarget dispatches events to listeners. DOM events can capture and bubble through the tree.',
`button.onclick=save; button.onclick=audit;`,
`button.addEventListener("click",save); button.addEventListener("click",audit);`,
`document.body.innerHTML='<div id="outer" style="padding:20px;background:#ddd"><button id="button">Click</button><p id="log"></p></div>'; const log=document.querySelector("#log"); document.querySelector("#outer").addEventListener("click",e=>log.textContent+=" outer"); document.querySelector("#button").addEventListener("click",e=>{log.textContent+=" button";console.log(e.target.id,e.currentTarget.id)});`,
'event',R(1,2,1,2,2),['onclick assignment replaces the previous handler.','Listeners can retain references for their lifetime.'],['Use currentTarget when you mean the object whose listener is executing.'],'dom'),

L('request-animation-frame','browser','requestAnimationFrame and visual work',MDN_RUNTIME.raf,
'requestAnimationFrame schedules a callback before the next repaint, making it the appropriate browser hook for animation updates.',
`setInterval(()=>box.style.left=(x++)+"px",16);`,
`function frame(){box.style.transform=\`translateX(\${x++}px)\`; requestAnimationFrame(frame)} requestAnimationFrame(frame);`,
`document.body.innerHTML='<div id="box" style="width:30px;height:30px;background:#222"></div><p id="status"></p>'; let x=0,frames=0; const box=document.querySelector("#box"); await new Promise(done=>{function frame(){x=(x+2)%180; box.style.transform=\`translateX(\${x}px)\`; document.querySelector("#status").textContent=\`frames: \${++frames}\`; if(frames<120)requestAnimationFrame(frame); else done()} requestAnimationFrame(frame)});`,
'render-pipeline',R(2,2,1,1,3),['A callback that itself does too much work can still miss frames.'],['Keep animation work small and prefer transform/opacity where appropriate.'],'dom'),

L('fetch-api','browser','Fetch API',MDN_RUNTIME.fetch,
'fetch() returns a Promise<Response>. HTTP error statuses normally resolve the promise; network-level failures reject.',
`const data=await fetch(url).then(r=>r.json());`,
`const response=await fetch(url); if(!response.ok)throw new Error(\`HTTP \${response.status}\`); const data=await response.json();`,
`console.log("Network disabled in this lab runner."); console.log("fetch returns Promise<Response>; check response.ok/status before parsing expected success data.");`,
'network',R(1,2,1,2,0,3),['404/500 responses do not automatically reject fetch.'],['Define status handling, cancellation and retry policy explicitly.']),

L('structured-clone','browser','Structured clone',MDN_RUNTIME.structuredClone,
'structuredClone copies many structured JavaScript values and can preserve cycles; it is also the basis for several browser messaging APIs.',
`const copy=JSON.parse(JSON.stringify(value));`,
`const copy=structuredClone(value);`,
`const original={date:new Date("2026-01-01T00:00:00Z"),map:new Map([["x",1]])}; original.self=original; const copy=structuredClone(original); console.log(copy.date instanceof Date,copy.map instanceof Map,copy.self===copy);`,
'memory',R(2,3,2),['Not every JavaScript value is cloneable.','Cloning large graphs costs CPU and memory.'],['Use transferables for large transferable buffers when copying would be wasteful.']),

L('web-workers','browser','Web Workers and parallel JavaScript',MDN_RUNTIME.workers,
'Workers run JavaScript in another agent, allowing CPU work to happen away from the page main thread. Communication uses messages/structured cloning or shared memory mechanisms.',
`// run expensive CPU loop on the main thread`,
`const worker=new Worker("worker.js"); worker.postMessage(data); worker.onmessage=e=>render(e.data);`,
`console.log("This code already runs in a disposable Web Worker."); console.log("window",typeof window,"document",typeof document,"self",typeof self,"postMessage",typeof postMessage);`,
'worker',R(2,2,1,1,0,0,1,3),['Dedicated workers cannot directly manipulate the page DOM.','Moving tiny work to a worker can cost more than it saves.'],['Use workers for meaningful CPU work when main-thread responsiveness matters.']),

L('web-storage','browser','Web Storage',MDN_RUNTIME.storage,
'localStorage/sessionStorage provide synchronous string-keyed storage associated with an origin.',
`localStorage.user=userObject;`,
`localStorage.setItem("user",JSON.stringify(userData));`,
`console.log("The isolated runner does not persist to the parent app."); console.log("Web Storage values are strings and persistent state needs schema/version handling.");`,
'storage',R(1,2,1,0,1),['Web Storage is synchronous.','Stored schemas need migrations/validation.'],['Keep persistent browser state small, explicit and recoverable.']),

L('websocket','browser','WebSocket and persistent connections',MDN_RUNTIME.websocket,
'WebSocket exposes a persistent two-way browser connection. The classic WebSocket API does not provide built-in backpressure.',
`socket.onmessage=e=>process(e.data); // unbounded processing assumed`,
`socket.onmessage=e=>{if(queue.length>=MAX_QUEUE)return shed(e.data); queue.push(e.data)};`,
`console.log("Network disabled in this lab."); console.log("Think: connecting → open → messages → closing/closed; your app owns queue/reconnect policy.");`,
'network',R(1,3,1,3,0,3),['Incoming messages can outrun processing and grow memory queues.'],['Model queue limits, reconnect behavior and application-level state explicitly.']),

L('performance-api','browser','Performance timing APIs',MDN_RUNTIME.performance,
'performance.now(), marks/measures and PerformanceObserver provide browser-side timing data without relying on Date wall-clock precision.',
`const start=Date.now(); doWork(); console.log(Date.now()-start);`,
`const start=performance.now(); doWork(); console.log(performance.now()-start);`,
`const start=performance.now(); let total=0; for(let i=0;i<1_000_000;i++)total+=i; console.log("elapsed ms",(performance.now()-start).toFixed(2),"total",total);`,
'performance',R(3,1,1),['One microbenchmark run is not a reliable performance conclusion.'],['Measure realistic workloads and distinguish wall time from CPU, heap and rendering pressure.'])
];