export const SOURCES = {
  mitAlgo: { name: 'MIT OpenCourseWare — Introduction to Algorithms', kind: 'University', url: 'https://ocw.mit.edu/courses/6-006-introduction-to-algorithms-fall-2011/' },
  clrs: { name: 'MIT Press — Introduction to Algorithms', kind: 'Reference', url: 'https://mitpress.mit.edu/9780262046305/introduction-to-algorithms/' },
  mdn: { name: 'MDN Web Docs', kind: 'Reference', url: 'https://developer.mozilla.org/' },
  nodeEvent: { name: 'Node.js — Don’t Block the Event Loop', kind: 'Official docs', url: 'https://nodejs.org/en/learn/asynchronous-work/dont-block-the-event-loop' },
  pythonTime: { name: 'Python Wiki — TimeComplexity', kind: 'Language reference', url: 'https://wiki.python.org/moin/TimeComplexity' },
  pythonCollections: { name: 'Python — collections', kind: 'Official docs', url: 'https://docs.python.org/3/library/collections.html' },
  pythonAsyncio: { name: 'Python — asyncio', kind: 'Official docs', url: 'https://docs.python.org/3/library/asyncio.html' },
  tsHandbook: { name: 'TypeScript Handbook', kind: 'Official docs', url: 'https://www.typescriptlang.org/docs/handbook/' },
  fowler: { name: 'Martin Fowler — Architecture & Design', kind: 'Practitioner', url: 'https://martinfowler.com/architecture/' },
  kleppmann: { name: 'Martin Kleppmann — Designing Data-Intensive Applications', kind: 'Reference', url: 'https://dataintensive.net/' },
  googleSre: { name: 'Google — Site Reliability Engineering', kind: 'Industry reference', url: 'https://sre.google/books/' },
  awsBuilders: { name: 'Amazon Builders’ Library', kind: 'Industry reference', url: 'https://aws.amazon.com/builders-library/' },
  postgres: { name: 'PostgreSQL Documentation', kind: 'Official docs', url: 'https://www.postgresql.org/docs/' },
  ietfHttp: { name: 'IETF RFC 9110 — HTTP Semantics', kind: 'Standard', url: 'https://www.rfc-editor.org/rfc/rfc9110' },
  websocket: { name: 'IETF RFC 6455 — WebSocket Protocol', kind: 'Standard', url: 'https://www.rfc-editor.org/rfc/rfc6455' },
  tls: { name: 'IETF RFC 8446 — TLS 1.3', kind: 'Standard', url: 'https://www.rfc-editor.org/rfc/rfc8446' },
  owasp: { name: 'OWASP Top 10', kind: 'Security reference', url: 'https://owasp.org/www-project-top-ten/' },
  owaspAsvs: { name: 'OWASP ASVS', kind: 'Security standard', url: 'https://owasp.org/www-project-application-security-verification-standard/' },
  nist: { name: 'NIST Secure Software Development Framework', kind: 'Standard', url: 'https://csrc.nist.gov/projects/ssdf' },
  grpc: { name: 'gRPC Documentation', kind: 'Official docs', url: 'https://grpc.io/docs/' },
  mcp: { name: 'Model Context Protocol — Specification', kind: 'Protocol docs', url: 'https://modelcontextprotocol.io/specification/' },
  openaiAgents: { name: 'OpenAI — Agents guide', kind: 'Official docs', url: 'https://developers.openai.com/api/docs/guides/agents' },
  openaiSafety: { name: 'OpenAI — Safety in building agents', kind: 'Official docs', url: 'https://developers.openai.com/api/docs/guides/agent-builder-safety' },
};

const L = (id, title, minutes, summary, config = {}) => ({ id, title, minutes, summary, ...config });
const T = (id, title, icon, description, labs) => ({ id, title, icon, description, labs });

export const TOPICS = [
  T('complexity', 'Complexity & performance', '◌', 'Reason precisely about time, space, hidden work, and language-specific traps.', [
    L('big-o', 'Growth rates & Big‑O', 20, 'Build a reliable mental model for O(1), O(log n), O(n), O(n log n), O(n²), and exponential growth.', {
      visual: 'growth', difficulty: 'Core', sources: ['mitAlgo','clrs'],
      objectives: ['Define the input size before naming complexity.', 'Distinguish O, Θ and Ω without overcomplicating the answer.', 'Recognise consecutive, nested, halving and monotonic-pointer loops.'],
      mentalModel: 'Complexity describes how resource use grows as the relevant input grows. It is not a stopwatch reading. Start by saying what n means, then count how many times the dominant operation can happen.',
      bullets: ['Drop constants only after identifying the real dominant work.', 'Two nested loops are not automatically O(n²): a monotonic inner pointer that never resets can make total work O(n).', 'Binary search is O(log n) because each step discards a constant fraction of the remaining search space.', 'O(n log n) commonly appears when n items each participate in logarithmic work, such as comparison sorting.'],
      traps: [
        ['“There are two loops, so O(n²)”', 'Ask whether the inner loop resets. If one pointer only advances across the whole input, total movement can still be O(n).'],
        ['Ignoring multiple inputs', 'For nested work over arrays of lengths n and m, O(n·m) is more informative than calling both n.'],
        ['Confusing measured speed with growth', 'A tiny O(n²) routine can beat O(n log n) for small n; asymptotics describe scaling, not constants.']
      ],
      tradeoffs: 'A strong answer pairs asymptotic complexity with the expected input range, constant factors, allocation behaviour, cache locality, and I/O boundaries.',
      exampleKind: 'membership', exerciseKind: 'twoSum'
    }),
    L('space', 'Space complexity & hidden allocations', 20, 'Separate input, output, auxiliary memory, stack depth, copies, and garbage-collection pressure.', {
      visual: 'memory', difficulty: 'Core', sources: ['mitAlgo','pythonTime','nodeEvent'],
      objectives: ['State auxiliary space separately from total memory.', 'Spot copies created by slicing, spreading, concatenation and immutable transformations.', 'Account for recursive call stacks.'],
      mentalModel: 'Ask “what new memory grows with the input?” Input storage already exists. Auxiliary space is extra working memory. Output may itself be Θ(n) and should be named separately.',
      bullets: ['An in-place loop can be O(1) auxiliary space even though the input occupies O(n).', 'Recursive depth d consumes O(d) stack frames unless the runtime eliminates them.', 'Repeated copying can turn apparently simple code into O(n²) time and large transient allocation volume.', 'Peak live memory matters more operationally than the total number of bytes ever allocated.'],
      traps: [['Returning an n-sized result but saying O(1) space', 'Clarify whether you mean auxiliary space. The output itself is still O(n).'], ['Hidden immutable copies', 'Array spread, list slicing and string concatenation may allocate data proportional to the copied value.'], ['GC is not free', 'High allocation rate can increase pause time and memory pressure even when asymptotic space looks acceptable.']],
      tradeoffs: 'Sometimes extra O(n) memory buys a large time improvement—hash sets, memoization and indexes are common deliberate space-for-time trades.',
      exampleKind: 'copying', exerciseKind: 'dedupe'
    }),
    L('amortized', 'Amortized & expected complexity', 20, 'Understand why occasional expensive operations can still produce cheap average cost over a sequence.', {
      visual: 'amortized', difficulty: 'Advanced', sources: ['mitAlgo','clrs'],
      objectives: ['Explain dynamic-array append as amortized O(1).', 'Separate average/expected hash-table behaviour from worst case.', 'Use aggregate reasoning rather than hand-waving “average”.'],
      mentalModel: 'Amortized analysis spreads infrequent expensive operations across many cheap operations in a sequence. Expected analysis depends on a probability model. They are different ideas.',
      bullets: ['A growing array occasionally copies O(n) elements, but geometric capacity growth makes total copying across n appends O(n).', 'Hash maps are typically expected/average O(1) for lookup under healthy hashing and load, not an unconditional worst-case guarantee.', 'A pathological collision pattern can degrade a hash structure; production runtimes use various mitigations.', 'Amortized bounds do not mean each individual operation is cheap.'],
      traps: [['Calling amortized “average case”', 'Amortized analysis can provide a deterministic bound over a sequence without assuming random inputs.'], ['Saying Map/Set is always O(1)', 'State the expected/typical hash-table assumption and note runtime implementation details.'], ['Ignoring latency spikes', 'Even with excellent amortized cost, a single resize may matter in a latency-sensitive path.']],
      tradeoffs: 'When tail latency matters, a structure with a slightly worse average but tighter per-operation bound may be preferable.',
      exampleKind: 'amortized', exerciseKind: 'boundedBuffer'
    }),
    L('recursion-dp', 'Recursion, recurrences & dynamic programming', 25, 'See how repeated subproblems create exponential work and how memoization changes both time and space.', {
      visual: 'recursion', difficulty: 'Advanced', sources: ['mitAlgo','clrs'],
      objectives: ['Estimate recursion-tree growth.', 'Recognise overlapping subproblems.', 'Explain memoization vs tabulation trade-offs.'],
      mentalModel: 'For recursive code, count branches and depth. A branching factor b over depth d can create roughly b^d calls unless branches terminate or repeated states are reused.',
      bullets: ['Naive Fibonacci repeats the same subproblems and grows exponentially.', 'Memoization trades O(n) storage for O(n) work in the classic Fibonacci example.', 'Divide-and-conquer such as merge sort has multiple branches but shrinking subproblems and combines to O(n log n).', 'Backtracking can be exponential even when each individual recursive frame looks small.'],
      traps: [['Only counting recursion depth', 'Depth gives stack space, not total number of calls. A shallow branching tree can still contain many nodes.'], ['Memoizing with the wrong key', 'The cache key must capture every part of state that affects the result.'], ['Copying state at every branch', 'Backtracking code can add another factor if each recursive call clones O(n) state.']],
      tradeoffs: 'Memoization improves repeated work but increases memory, cache-management complexity, and sometimes changes failure modes under unbounded state.',
      exampleKind: 'fibonacci', exerciseKind: 'climbStairs'
    }),
    L('js-complexity', 'JavaScript / TypeScript complexity traps', 25, 'Identify innocent-looking JS/TS idioms that hide repeated scans, copies, event-loop blocking, or unbounded fan-out.', {
      visual: 'eventloop', difficulty: 'Language', sources: ['mdn','nodeEvent','tsHandbook'],
      objectives: ['Know common Array, Set and Map cost patterns.', 'Spot sequential await and unbounded Promise.all trade-offs.', 'Reason about event-loop responsiveness as well as Big‑O.'],
      mentalModel: 'In JS/TS, asymptotic work and event-loop behaviour both matter. CPU-heavy O(n) code can still be harmful when n is large because one thread may monopolise the event loop.',
      bullets: ['Array.includes/indexOf/find are linear scans.', 'shift/unshift move array elements conceptually and are poor queue primitives at scale.', 'Repeated [...arr, x] copies the existing array each iteration.', 'Promise.all reduces wall-clock latency for independent I/O but does not reduce total operations and can overwhelm dependencies if unbounded.'],
      traps: [['Set.has as a magic fix', 'Building the Set itself costs time and memory. It pays off when you perform enough membership queries.'], ['Sequential await in an independent loop', 'Correctness may be fine, but independent I/O becomes unnecessarily serial.'], ['“Async means non-blocking”', 'Async APIs help with waiting; CPU-bound JavaScript still consumes the event-loop thread unless moved elsewhere.']],
      tradeoffs: 'Choose concurrency limits based on downstream capacity, memory, rate limits and failure amplification—not merely the shortest benchmark.',
      exampleKind: 'jsTraps', exerciseKind: 'boundedConcurrency'
    }),
    L('python-complexity', 'Python complexity traps', 25, 'Understand list/deque choices, membership scans, slicing, generators, copying, and asyncio pitfalls.', {
      visual: 'queue', difficulty: 'Language', sources: ['pythonTime','pythonCollections','pythonAsyncio'],
      objectives: ['Choose list vs deque intentionally.', 'Spot list membership and front-removal costs.', 'Use generators when streaming is more appropriate than materialising.'],
      mentalModel: 'Python’s expressive operations can hide whole-input work. Ask what an operation must scan, copy, allocate or shift under the hood.',
      bullets: ['x in list is O(n); x in set/dict is typically expected O(1).', 'list.pop(0) is O(n); collections.deque.popleft() is approximately O(1).', 's[:] creates a copy proportional to slice length.', 'list(generator) materialises all results; iterating the generator can keep auxiliary memory bounded.'],
      traps: [['Using a list as a FIFO queue', 'Front removal repeatedly shifts the remaining elements. Use deque when both ends matter.'], ['Rebuilding set(items) inside a loop', 'You pay O(n) construction repeatedly; build once when the source is unchanged.'], ['Assuming asyncio speeds CPU work', 'asyncio improves cooperative I/O concurrency; CPU-heavy functions still block the event loop.']],
      tradeoffs: 'Python often rewards choosing the right built-in data structure over micro-optimising syntax.',
      exampleKind: 'pythonTraps', exerciseKind: 'firstUnique'
    }),
    L('systems-complexity', 'Complexity across system boundaries', 20, 'Extend complexity reasoning to database calls, network fan-out, serialization, pagination and concurrency.', {
      visual: 'nplusone', difficulty: 'Advanced', sources: ['googleSre','awsBuilders','postgres'],
      objectives: ['Recognise N+1 I/O patterns.', 'Reason about remote-call count as an input dimension.', 'Separate total work, wall-clock latency and resource contention.'],
      mentalModel: 'At system scale, a remote call is not “O(1)” in the useful sense. Count the number of calls, bytes, rows, partitions and fan-out targets, then discuss latency and failure amplification.',
      bullets: ['Fetching one page plus one query per row creates O(n) round trips even if each query is indexed.', 'Batching can reduce call count while increasing payload size and memory.', 'Parallel fan-out can reduce latency but increases simultaneous load and broadens the failure surface.', 'Serialization/deserialization is O(bytes), which matters for large JSON payloads and hot APIs.'],
      traps: [['Only analysing in-process loops', 'Production bottlenecks frequently come from remote calls and data volume rather than CPU instructions.'], ['Parallelising N+1 blindly', 'You may trade slow latency for database overload. Fix query shape before adding concurrency.'], ['Ignoring output size', 'No algorithm can emit k output items in less than Ω(k) work to actually materialise them.']],
      tradeoffs: 'A strong design balances algorithmic work, round trips, data volume, concurrency limits and tail latency.',
      exampleKind: 'nplusone', exerciseKind: 'batchLoader'
    }),
  ]),

  T('algorithms', 'Data structures & algorithms', '⌁', 'Use the right structures, recognise invariants, and explain algorithmic trade-offs.', [
    L('structures', 'Arrays, maps, sets, stacks & queues', 20, 'Know the operations that make each structure the right tool.', { visual:'structures', sources:['mitAlgo','pythonCollections'], objectives:['Map operations to workload needs.','Explain order, uniqueness and access patterns.','Avoid using arrays/lists for every problem.'], mentalModel:'Pick a structure by the operation you need to make cheap: indexed access, membership, priority, FIFO/LIFO, ordered traversal or range queries.', bullets:['Arrays/lists excel at indexed traversal and locality.','Hash maps/sets trade memory for fast expected key access.','Stacks model nested state; queues model arrival order; deques support both ends.','Heaps make repeated min/max extraction efficient.'], traps:[['Choosing by familiarity','Start from required operations and invariants, not your favourite structure.'],['Forgetting iteration order','Some APIs preserve insertion order; that is distinct from sorted order.']], tradeoffs:'A more specialised structure can make one operation dramatically cheaper at the cost of memory or other operations.', exampleKind:'membership', exerciseKind:'lruMini' }),
    L('search-sort', 'Searching, sorting & two pointers', 20, 'Know when sorting first enables a simpler or faster downstream algorithm.', { visual:'sorting', sources:['mitAlgo','clrs'], objectives:['Explain binary-search preconditions.','Compare sort-then-scan with hash-based approaches.','Recognise two-pointer and sliding-window invariants.'], mentalModel:'Sorting costs O(n log n), but it buys order. Order can turn later scans, merging, deduplication and range reasoning into linear or logarithmic work.', bullets:['Binary search requires a monotonic predicate or ordered search space.','Two pointers can make nested-looking logic O(n) when each pointer advances monotonically.','Stable sorting preserves relative order among equal keys.','Comparison sorting has a Ω(n log n) lower bound in the general comparison model.'], traps:[['Binary searching unsorted data','The algorithm is fast only when its ordering invariant holds.'],['Sorting when one lookup would do','A hash map may solve a one-shot membership problem in O(n) expected time without O(n log n) sorting.']], tradeoffs:'Sorting may be preferable when you need deterministic ordering, range operations, low extra memory, or repeated ordered queries.', exampleKind:'sortVsSet', exerciseKind:'mergeIntervals' }),
    L('trees-graphs', 'Trees, heaps & graphs', 25, 'Reason about traversal, shortest paths, priority queues and graph representation.', { visual:'graph', sources:['mitAlgo','clrs'], objectives:['Know BFS vs DFS behaviour.','Choose adjacency list vs matrix.','Explain heap use in priority-driven algorithms.'], mentalModel:'Graphs are relationships. Complexity usually depends on both vertices V and edges E, so say O(V+E) rather than collapsing everything into n.', bullets:['BFS explores by distance in unweighted graphs.','DFS is natural for reachability, components, topological reasoning and backtracking.','Adjacency lists use O(V+E) space; matrices use O(V²).','A binary heap supports insert/extract-priority in O(log n).'], traps:[['Forgetting visited state','Cycles turn naive traversals into repeated or infinite work.'],['Using BFS for weighted shortest path','Dijkstra handles non-negative weighted edges; BFS assumes equal edge cost.']], tradeoffs:'Representation is workload-dependent: dense graphs may justify matrices; sparse graphs usually favour adjacency lists.', exampleKind:'graph', exerciseKind:'shortestUnweighted' }),
  ]),

  T('concurrency', 'Concurrency & async', '⇄', 'Reason about races, event loops, locks, bounded parallelism, and backpressure.', [
    L('async-models', 'Event loops, threads & async models', 20, 'Separate concurrency from parallelism and understand runtime execution models.', { visual:'eventloop', sources:['nodeEvent','pythonAsyncio'], objectives:['Define concurrency vs parallelism.','Explain JS event-loop constraints.','Explain Python asyncio’s cooperative model.'], mentalModel:'Concurrency is about managing multiple in-flight tasks; parallelism is simultaneous execution. Async I/O mostly improves waiting time, not CPU complexity.', bullets:['JavaScript typically runs user code on one event-loop thread while I/O completes elsewhere.','Python asyncio schedules coroutines cooperatively on an event loop.','CPU-heavy work requires workers/processes/threads or native parallel execution depending on runtime.'], traps:[['Adding async to CPU code','It does not make the CPU work disappear.'],['Blocking calls in an async handler','One blocking call can stall unrelated requests on the same event loop.']], tradeoffs:'Pick a concurrency model based on I/O vs CPU profile, isolation needs, scheduling overhead and operational simplicity.', exampleKind:'async', exerciseKind:'boundedConcurrency' }),
    L('races-locks', 'Races, locks & atomicity', 25, 'Find race conditions and reason about critical sections instead of sprinkling locks.', { visual:'race', sources:['kleppmann','googleSre'], objectives:['Identify read-modify-write races.','Minimise critical sections.','Recognise deadlock preconditions.'], mentalModel:'A race appears when correctness depends on timing between operations that are not atomic as a group. Protect the invariant, not individual lines.', bullets:['Check-then-act operations are classic race candidates.','A lock should cover the state transition that must be atomic.','Multiple locks introduce ordering and deadlock concerns.','Optimistic concurrency uses versions/CAS and retries rather than exclusive locking.'], traps:[['Locking too little','Protecting the write but not the preceding read may leave the race intact.'],['Locking everything','A global lock preserves correctness but may destroy throughput.']], tradeoffs:'Pessimistic locking reduces conflicts at the cost of blocking; optimistic control improves concurrency when conflicts are rare.', exampleKind:'race', exerciseKind:'versionedCounter' }),
    L('backpressure', 'Backpressure & bounded concurrency', 20, 'Keep fast producers from overwhelming slower consumers.', { visual:'queue', sources:['awsBuilders','googleSre'], objectives:['Recognise unbounded queues and fan-out.','Use concurrency limits.','Connect queue depth to latency and overload.'], mentalModel:'If producers can create work faster than consumers finish it, the excess must wait, be rejected, be shed, or push pressure upstream.', bullets:['Unbounded queues convert overload into memory growth and terrible tail latency.','Concurrency limits protect dependencies and your own process.','Load shedding can be healthier than accepting work you cannot finish within an SLO.'], traps:[['Promise.all over 100k items','You may create enormous simultaneous pressure even though code looks elegant.'],['Retrying overload','Retries can multiply traffic and worsen an incident.']], tradeoffs:'Throughput, fairness, latency and resource protection pull in different directions; limits should be explicit and observable.', exampleKind:'bounded', exerciseKind:'boundedConcurrency' }),
  ]),

  T('system-design', 'System design', '◇', 'Turn vague requirements into scalable, operable architectures and defend the trade-offs.', [
    L('requirements', 'Requirements, scale & SLOs', 20, 'Start design interviews by making the problem measurable.', { visual:'requirements', sources:['googleSre','awsBuilders'], objectives:['Separate functional and non-functional requirements.','Estimate traffic and data volume.','Define latency/availability targets.'], mentalModel:'A design cannot be judged without workload and goals. Clarify users, operations, read/write mix, object size, growth, latency, durability and consistency needs first.', bullets:['Back-of-the-envelope estimates expose orders of magnitude.','Peak load matters more than average for capacity.','SLOs turn “fast” and “reliable” into testable targets.'], traps:[['Drawing boxes immediately','You may optimise for constraints the interviewer never asked for.'],['False precision','Use rounded assumptions and explain them.']], tradeoffs:'Stronger guarantees and lower latency usually cost capacity, complexity, or availability elsewhere.', exampleKind:'requirements', exerciseKind:'capacityEstimate' }),
    L('scaling-cache', 'Caching, load balancing & scaling', 25, 'Understand the mechanics and failure modes behind common scale-out techniques.', { visual:'cache', sources:['awsBuilders','googleSre'], objectives:['Choose cache location and key.','Explain invalidation strategies.','Recognise hot keys and stampedes.'], mentalModel:'A cache is a deliberately stale duplicate optimised for a read path. It reduces repeated work but creates freshness and invalidation problems.', bullets:['Cache-aside is simple but has miss and stampede behaviour.','TTL bounds staleness but does not guarantee freshness.','Load balancers distribute requests; stateful sessions complicate horizontal scale.','Hot keys can overload one cache shard even when total capacity is ample.'], traps:[['Caching everything','Low-hit or highly volatile data may cost more to cache than to compute.'],['No invalidation story','Every cache design needs a freshness model.']], tradeoffs:'Cache hit rate, staleness tolerance, memory cost and failure behaviour should be explicit.', exampleKind:'cache', exerciseKind:'cacheAside' }),
    L('queues-workers', 'Queues, workers & asynchronous workflows', 20, 'Use messaging when work can be decoupled in time, then reason about delivery semantics.', { visual:'queue', sources:['kleppmann','awsBuilders'], objectives:['Explain at-least-once delivery.','Design idempotent consumers.','Use dead-letter handling deliberately.'], mentalModel:'A queue trades immediate completion for decoupling and smoothing. It does not magically guarantee exactly-once business effects.', bullets:['At-least-once delivery means duplicates are normal.','Consumer idempotency converts duplicate delivery into safe repeated processing.','Queue depth is a backlog and latency signal.','Poison messages need retry limits and an operational path.'], traps:[['Exactly-once hand waving','Transport semantics do not automatically make side effects exactly once.'],['Infinite retries','Permanent failures become permanent load.']], tradeoffs:'Async workflows improve resilience and smoothing but add eventual completion, observability and reconciliation complexity.', exampleKind:'queueSystem', exerciseKind:'idempotentConsumer' }),
  ]),

  T('distributed', 'Distributed systems', '⟷', 'Master consistency, replication, partitions, idempotency and failure-aware design.', [
    L('consistency', 'Consistency models & eventual consistency', 25, 'Use precise language for what reads are allowed to observe.', { visual:'consistency', sources:['kleppmann'], objectives:['Contrast linearizability and eventual consistency.','Explain read-your-writes and monotonic reads.','Connect consistency to product semantics.'], mentalModel:'Consistency is a contract about which histories clients may observe. “Eventual” means replicas converge after writes stop; it does not mean “usually correct”.', bullets:['Linearizable systems behave as if operations occur atomically in one real-time order.','Eventual consistency allows temporary divergence but requires convergence.','Session guarantees can provide useful middle ground for user experience.'], traps:[['CAP as “pick any two”','CAP speaks specifically about behaviour during a network partition.'],['Calling stale reads data loss','Staleness and durability are different properties.']], tradeoffs:'The right consistency level depends on invariants: likes can tolerate lag; money movement usually needs stronger coordination.', exampleKind:'consistency', exerciseKind:'versionConflict' }),
    L('replication-quorum', 'Replication, quorum & failover', 25, 'Reason about leaders, replicas, lag and quorum intersections.', { visual:'replication', sources:['kleppmann'], objectives:['Explain leader/follower replication.','Reason about R+W>N quorum intuition.','Understand replication lag and failover hazards.'], mentalModel:'Replication creates copies for availability/read scale/durability, but copies must agree on ordering and freshness.', bullets:['Synchronous replication raises write latency but can reduce acknowledged-data loss.','Asynchronous followers may lag and serve stale reads.','Failover must avoid split brain and stale leaders.'], traps:[['“Three replicas means no data loss”','Durability depends on acknowledgement policy and failure timing.'],['Ignoring lag after failover','A promoted replica may be missing recently acknowledged writes in some designs.']], tradeoffs:'More coordination improves consistency but costs latency and availability under faults.', exampleKind:'replication', exerciseKind:'quorumCalc' }),
    L('idempotency-sagas', 'Idempotency, retries & sagas', 25, 'Make multi-step workflows survive duplicates and partial failure.', { visual:'saga', sources:['awsBuilders','fowler'], objectives:['Design idempotency keys.','Use compensating actions.','Distinguish retryable from terminal failure.'], mentalModel:'Distributed workflows fail between steps. Design every boundary assuming the caller may not know whether the previous attempt took effect.', bullets:['Idempotency keys identify one logical operation across retries.','Sagas coordinate local transactions with compensating actions rather than one global ACID transaction.','Timeouts create uncertainty, not proof of failure.'], traps:[['Retrying non-idempotent writes blindly','The original may have succeeded even though the response was lost.'],['Compensation as perfect rollback','External effects may be irreversible or only approximately compensatable.']], tradeoffs:'Sagas trade atomicity for availability and autonomy, then require reconciliation and business-aware compensation.', exampleKind:'idempotency', exerciseKind:'idempotencyKey' }),
  ]),

  T('architecture', 'Architecture & design', '⬡', 'Design boundaries that keep change local, dependencies explicit, and systems evolvable.', [
    L('principles', 'Cohesion, coupling & SOLID', 20, 'Use design principles as diagnostic tools rather than rules to recite.', { visual:'modules', sources:['fowler'], objectives:['Explain cohesion and coupling.','Apply dependency inversion pragmatically.','Avoid abstraction for abstraction’s sake.'], mentalModel:'Good boundaries put things that change together in the same place and minimise knowledge between things that change independently.', bullets:['High cohesion makes a module’s responsibilities belong together.','Low coupling reduces the blast radius of change.','Dependency inversion means high-level policy should not depend directly on volatile low-level details.'], traps:[['One interface per class','SOLID is about changeability and substitutability, not ceremony.'],['DRY too early','Two similar snippets may represent different concepts that should evolve independently.']], tradeoffs:'Abstraction reduces duplication only when the shared concept is stable; otherwise it can couple unrelated change.', exampleKind:'design', exerciseKind:'refactorBoundary' }),
    L('modular', 'Modular monolith vs microservices', 25, 'Choose deployment boundaries based on organisational and operational needs.', { visual:'architecture', sources:['fowler'], objectives:['Separate logical modularity from deployment topology.','Recognise distributed-systems tax.','Identify service-boundary signals.'], mentalModel:'Microservices turn in-process calls into network calls and team boundaries into operational boundaries. A modular monolith can preserve strong internal boundaries without that tax.', bullets:['Independent deployability is a major benefit only if teams and changes need it.','Distributed transactions, observability and failure handling become harder across services.','A monolith can still be well modularised and horizontally scaled.'], traps:[['Microservices for “scale” by default','Many monoliths scale far beyond the needs of most products.'],['Shared database across “services”','This often preserves coupling while adding network complexity.']], tradeoffs:'Optimise for rate of change, ownership, isolation and operational maturity—not architecture fashion.', exampleKind:'architecture', exerciseKind:'boundaryDecision' }),
    L('cqrs-events', 'CQRS, event sourcing & hexagonal architecture', 25, 'Understand three often-misused architectural patterns and when they earn their complexity.', { visual:'cqrs', sources:['fowler'], objectives:['Define CQRS precisely.','Separate event sourcing from event-driven messaging.','Explain ports and adapters.'], mentalModel:'Patterns solve specific forces. CQRS separates write and read models; event sourcing stores state changes as an event log; hexagonal architecture isolates domain policy behind ports.', bullets:['CQRS can allow read models tailored to queries but adds synchronisation complexity.','Event sourcing gives history and replay but makes schema evolution and projections real concerns.','Ports/adapters keep domain logic independent of transport and persistence details.'], traps:[['Event-driven = event sourced','Publishing domain events does not imply events are the source of truth.'],['CQRS everywhere','Simple CRUD often does not justify two models.']], tradeoffs:'These patterns buy flexibility and auditability by accepting more moving parts, eventual consistency and tooling needs.', exampleKind:'cqrs', exerciseKind:'commandQuery' }),
  ]),

  T('networking', 'HTTP, protocols & networking', '↗', 'Understand the protocols underneath APIs and real-time systems.', [
    L('http', 'HTTP semantics, caching & idempotency', 25, 'Reason about methods, status codes, headers, caching and retries.', { visual:'http', sources:['ietfHttp','mdn'], objectives:['Use safe/idempotent method semantics correctly.','Understand cache validators.','Design retry-aware APIs.'], mentalModel:'HTTP is a semantic protocol, not just JSON over TCP. Method meaning, caching rules and status codes are part of the contract.', bullets:['GET is safe and idempotent; PUT and DELETE are idempotent by semantics; POST is not inherently idempotent.','ETag/If-None-Match support validation without transferring a full representation.','4xx generally represents client-side request issues; 5xx represents server-side inability to fulfil.'], traps:[['GET with side effects','Retries, crawlers and caches assume safe semantics.'],['200 for every outcome','You discard useful protocol semantics and tooling behaviour.']], tradeoffs:'Protocol conventions reduce bespoke client logic and make caches, gateways and observability work with you.', exampleKind:'http', exerciseKind:'httpHandler' }),
    L('realtime', 'WebSockets, SSE & polling', 20, 'Choose the simplest real-time transport that matches message direction and scale.', { visual:'realtime', sources:['websocket','mdn'], objectives:['Compare full-duplex WebSocket with one-way SSE.','Account for reconnects and ordering.','Discuss load-balancer implications.'], mentalModel:'Use the transport that matches communication direction. SSE is server→client over HTTP; WebSocket is a long-lived full-duplex channel; polling creates repeated requests.', bullets:['WebSockets suit interactive bidirectional sessions.','SSE has built-in browser reconnection semantics and works well for server push.','Polling is simplest operationally and may be perfectly adequate at low frequency.'], traps:[['WebSockets by default','You inherit connection state, heartbeats, fan-out and reconnect complexity.'],['Ignoring backpressure','A slow client can accumulate unsent messages.']], tradeoffs:'Latency, directionality, connection count, intermediaries and operational complexity matter more than novelty.', exampleKind:'realtime', exerciseKind:'transportChoice' }),
    L('transport-security', 'DNS, TCP, TLS & gRPC', 25, 'Build the path from hostname to secure application request.', { visual:'networkStack', sources:['tls','grpc'], objectives:['Explain DNS resolution at a high level.','Distinguish TCP reliability from TLS confidentiality/authentication.','Know what gRPC adds.'], mentalModel:'A request traverses layers: naming finds an address, transport moves bytes, TLS authenticates/encrypts, and application protocols define message semantics.', bullets:['TCP provides an ordered reliable byte stream; it does not encrypt.','TLS authenticates peers (typically the server) and protects data in transit.','gRPC commonly uses HTTP/2 plus protobuf contracts and supports streaming.'], traps:[['TLS means authorised','Encryption/authentication of the endpoint does not replace application authorisation.'],['TCP message boundaries','TCP is a byte stream; application protocols define framing.']], tradeoffs:'Binary RPC can improve contract/tooling efficiency but may be less browser-friendly and human-readable than JSON HTTP APIs.', exampleKind:'network', exerciseKind:'protocolLayers' }),
  ]),

  T('databases', 'Databases & storage', '▤', 'Understand indexes, transactions, isolation, replication and data-model trade-offs.', [
    L('indexes', 'Indexes, B‑trees & query shape', 25, 'Know why indexes speed some queries and make writes more expensive.', { visual:'btree', sources:['postgres'], objectives:['Explain B-tree lookup intuition.','Recognise composite-index ordering.','Connect query shape to index usefulness.'], mentalModel:'An index is another data structure maintained alongside the table. It avoids scanning everything by maintaining searchable order or another access structure.', bullets:['B-tree indexes support equality and ordered/range access patterns.','Every additional index consumes storage and adds write maintenance.','A composite index’s leading columns strongly influence which predicates it can serve efficiently.'], traps:[['Index every column','Writes and storage suffer, and many indexes may never be used.'],['Assuming index means O(1)','Tree indexes are logarithmic in structure, while end-to-end query cost also includes fetched rows and I/O.']], tradeoffs:'Index for real query patterns, then verify with the query planner and production-like data.', exampleKind:'index', exerciseKind:'indexChoice' }),
    L('transactions', 'Transactions, isolation & MVCC', 25, 'Reason about concurrent database changes using anomalies instead of vague “ACID”.', { visual:'transactions', sources:['postgres','kleppmann'], objectives:['Know atomicity/durability vs isolation.','Recognise dirty/non-repeatable/phantom style anomalies.','Understand MVCC intuition.'], mentalModel:'Isolation determines which concurrent histories the database permits. MVCC often lets readers observe a snapshot without blocking writers in the simplest cases.', bullets:['Atomicity groups effects of one transaction; durability concerns committed data surviving failure.','Isolation levels trade coordination and anomalies.','Serializable aims to make concurrent execution equivalent to some serial order.'], traps:[['Transaction = no races','The chosen isolation level may still permit application-visible anomalies.'],['Long transactions','They can retain old versions, locks or resources and increase contention.']], tradeoffs:'Use the weakest isolation level that still protects your invariants—after you can state those invariants precisely.', exampleKind:'transaction', exerciseKind:'lostUpdate' }),
    L('data-model', 'Normalization, denormalization & partitioning', 20, 'Shape data for correctness and access patterns, then understand the cost of distributing it.', { visual:'partition', sources:['kleppmann','postgres'], objectives:['Explain normalization benefits.','Know why denormalization creates synchronisation work.','Choose partition keys carefully.'], mentalModel:'Data modelling decides where facts live and how often they must be duplicated. Partitioning decides where those facts physically/logically live across nodes.', bullets:['Normalization reduces redundant facts and update anomalies.','Denormalization can make reads cheaper at the cost of keeping copies consistent.','A poor partition key creates hotspots or expensive cross-partition operations.'], traps:[['Denormalize before measuring','You can inherit consistency complexity without a proven read bottleneck.'],['Partition by a hot tenant','One key can dominate one shard and defeat horizontal scale.']], tradeoffs:'Model for the invariants and dominant access paths, while preserving an escape route as workload changes.', exampleKind:'partition', exerciseKind:'partitionKey' }),
  ]),

  T('security', 'Secure coding', '⛨', 'Design trust boundaries, validate input, enforce authorization, and defend AI/tooling surfaces.', [
    L('input-output', 'Injection, XSS & input/output handling', 25, 'Treat untrusted input as data and encode at the correct sink.', { visual:'securityBoundary', sources:['owasp','owaspAsvs'], objectives:['Use parameterised queries.','Distinguish validation from output encoding.','Recognise command/template injection.'], mentalModel:'Security depends on context. The same string may be safe as plain text and dangerous when interpreted as SQL, HTML, shell syntax or a template.', bullets:['Parameterised SQL keeps values separate from query structure.','HTML output encoding is sink-specific protection against XSS.','Allowlist validation is strongest when the domain of valid values is known.'], traps:[['Escaping once for every context','SQL, HTML, URLs and shells have different grammars.'],['Regex as complete security model','Validation helps, but use safe APIs that avoid interpretation in the first place.']], tradeoffs:'Prefer designs where untrusted values never become executable syntax.', exampleKind:'injection', exerciseKind:'secureQuery' }),
    L('auth', 'Authentication, authorization & sessions', 25, 'Keep identity proof separate from permission decisions.', { visual:'auth', sources:['owaspAsvs','nist'], objectives:['Distinguish authN and authZ.','Enforce object-level authorization server-side.','Protect sessions/tokens.'], mentalModel:'Authentication answers “who are you?” Authorization answers “may this identity perform this action on this resource?” Every request needs the appropriate decision.', bullets:['Never rely on hidden UI controls for authorization.','BOLA/IDOR occurs when a valid user can access another user’s object by changing an identifier.','Short-lived credentials reduce exposure; refresh/session mechanisms need revocation and rotation strategies.'], traps:[['Role check without resource check','“User” may be allowed to read a user document, but not every user document.'],['JWT means stateless security solved','Token lifetime, revocation, key rotation and audience/issuer validation still matter.']], tradeoffs:'Centralised policy can improve consistency but becomes a critical dependency; embedded checks can drift.', exampleKind:'auth', exerciseKind:'authorizeObject' }),
    L('ssrf-secrets', 'SSRF, secrets & dependency security', 25, 'Protect outbound network capability, credentials and software supply chains.', { visual:'ssrf', sources:['owasp','nist'], objectives:['Threat-model server-side fetches.','Keep secrets out of code/logs.','Pin and monitor dependencies.'], mentalModel:'Server-side code often has more network and credential authority than the user. Anything that lets users influence destinations can become a pivot into trusted infrastructure.', bullets:['SSRF defenses combine strict destination policy, URL parsing, DNS/IP checks and network egress controls.','Secrets belong in managed secret stores or protected runtime configuration, not repositories.','Dependency risk includes malicious packages, compromised maintainers and vulnerable transitive code.'], traps:[['Blocking localhost strings only','Alternate IP encodings, redirects and DNS rebinding can bypass naive filters.'],['Redacting only known secret keys','Secrets can leak through arbitrary payloads, traces and exception messages.']], tradeoffs:'Defense in depth matters because parsers and application checks can fail; egress policy limits the blast radius.', exampleKind:'ssrf', exerciseKind:'urlPolicy' }),
  ]),

  T('reliability', 'Reliability & observability', '⌁', 'Design for failure, measure user-visible reliability, and debug with evidence.', [
    L('slo', 'SLIs, SLOs, SLAs & error budgets', 20, 'Turn reliability into measurable product behaviour.', { visual:'slo', sources:['googleSre'], objectives:['Define SLI/SLO/SLA.','Calculate an error budget conceptually.','Use SLOs to prioritise reliability work.'], mentalModel:'An SLI is a measurement, an SLO is a target for that measurement, and an SLA is an external commitment with consequences. The error budget is the allowed unreliability within the SLO.', bullets:['Availability should be measured from the user’s perspective when possible.','100% targets can prevent healthy change and are often unrealistic.','Error-budget burn rate shows whether you are consuming reliability too quickly.'], traps:[['Uptime only','A service can be “up” while returning slow or incorrect responses.'],['SLA = SLO','Internal targets are usually tighter than external commitments.']], tradeoffs:'Reliability competes with feature velocity; error budgets make that trade visible.', exampleKind:'slo', exerciseKind:'errorBudget' }),
    L('resilience', 'Timeouts, retries, backoff & circuit breakers', 25, 'Prevent small dependency failures from turning into system-wide overload.', { visual:'retries', sources:['awsBuilders','googleSre'], objectives:['Always pair remote calls with timeouts.','Use backoff and jitter.','Know what circuit breakers protect.'], mentalModel:'Retries are extra load. They are useful only when failures are transient and the operation is safe to repeat.', bullets:['Timeouts bound how long scarce resources wait.','Exponential backoff reduces retry pressure; jitter prevents synchronised retry waves.','Circuit breakers stop repeatedly calling a dependency that is clearly failing.'], traps:[['Retry every error','Validation errors and many 4xx-style outcomes will not improve on retry.'],['Retries at every layer','Multiplicative retries can explode call volume.']], tradeoffs:'Fast failure protects capacity but can reduce success for brief recoverable blips; policies should match dependency behaviour.', exampleKind:'retry', exerciseKind:'retryPolicy' }),
    L('observability', 'Logs, metrics, traces & debugging', 20, 'Use each telemetry type for the question it answers best.', { visual:'trace', sources:['googleSre'], objectives:['Separate metrics/logs/traces.','Use correlation IDs carefully.','Instrument boundaries and latency.'], mentalModel:'Metrics tell you that something changed, traces show where time went across a request, and logs provide detailed event context. None replaces the others.', bullets:['High-cardinality labels can make metrics systems expensive.','Structured logs are easier to query than free-form strings.','Distributed traces need context propagation across boundaries.'], traps:[['Logging everything','Noise, cost and secret leakage grow quickly.'],['Only average latency','Tail percentiles often reveal the user-visible pain.']], tradeoffs:'Observability is a product feature with storage, privacy and runtime costs—instrument what supports decisions.', exampleKind:'observability', exerciseKind:'telemetryChoice' }),
  ]),

  T('testing', 'Testing & delivery', '✓', 'Build confidence with the right test layers and safe deployment mechanics.', [
    L('test-strategy', 'Unit, integration, contract & E2E tests', 20, 'Pick the smallest test scope that proves the risk you care about.', { visual:'testPyramid', sources:['fowler'], objectives:['Choose test type by failure mode.','Avoid over-mocking boundaries.','Understand contract testing.'], mentalModel:'Tests buy confidence. Narrow tests are fast and precise; broader tests catch integration failures but cost more to run and debug.', bullets:['Unit tests are excellent for deterministic domain logic.','Integration tests verify real boundaries such as databases or queues.','Contract tests protect independently deployed producer/consumer assumptions.','E2E tests prove critical user journeys but should not carry every edge case.'], traps:[['Mocking your own misunderstandings','A mock can happily implement the wrong contract.'],['Only happy-path E2E','You get slow tests without strong edge-case coverage.']], tradeoffs:'Optimise the portfolio for feedback speed and risk, not a fixed pyramid ratio.', exampleKind:'testing', exerciseKind:'testBoundary' }),
    L('delivery', 'CI/CD, feature flags & rollback', 20, 'Reduce batch size and make production change reversible.', { visual:'pipeline', sources:['googleSre'], objectives:['Separate deploy from release.','Use flags safely.','Design rollback-compatible changes.'], mentalModel:'A safe delivery system makes small changes observable and reversible. Feature flags decouple code deployment from feature exposure.', bullets:['Small changes reduce debugging search space.','Feature flags need ownership and deletion or they become permanent complexity.','Database migrations often require expand/contract sequencing for rollback compatibility.'], traps:[['Rollback as the only plan','Schema/data changes may not be reversible by simply redeploying old code.'],['Long-lived flags','Branches in production accumulate combinatorial test states.']], tradeoffs:'Progressive delivery reduces blast radius but requires telemetry and operational discipline.', exampleKind:'delivery', exerciseKind:'migrationOrder' }),
    L('quality', 'Property testing, fuzzing & invariants', 20, 'Test properties that should hold across many generated inputs.', { visual:'fuzz', sources:['owasp','fowler'], objectives:['Define invariants.','Use generated inputs for edge discovery.','Distinguish example tests from properties.'], mentalModel:'Example tests prove specific cases. Property tests state rules that should hold for many cases, while fuzzers search for crashes and unexpected states.', bullets:['Round-trip encode/decode is a classic property.','Parsers, protocol handlers and validation code benefit from fuzzing.','Shrinking reduces a failing generated case to a minimal counterexample.'], traps:[['A vague property','The test is only useful if failure has clear meaning.'],['Randomness without reproducibility','Persist seeds/counterexamples so failures can be replayed.']], tradeoffs:'Generated testing complements, rather than replaces, carefully chosen domain examples.', exampleKind:'property', exerciseKind:'propertyTest' }),
  ]),

  T('ai', 'AI engineering & MCP', '✦', 'Design LLM systems, retrieval, tool use, evals, and secure MCP integrations.', [
    L('llm-design', 'LLM application architecture', 25, 'Treat model calls as probabilistic components inside deterministic product boundaries.', { visual:'llmPipeline', sources:['openaiAgents'], objectives:['Separate orchestration from model reasoning.','Control context and outputs.','Design graceful fallbacks.'], mentalModel:'An LLM is a component that maps context to probabilistic output. Reliable products constrain inputs/outputs, keep deterministic state outside the model, and observe failures.', bullets:['Context windows are finite; more context is not automatically better context.','Structured outputs reduce downstream parsing ambiguity.','Deterministic business rules should stay in deterministic code when practical.','Latency and token use are architectural constraints.'], traps:[['Putting application state only in prompts','The model is not your durable database.'],['One giant agent prompt','Smaller explicit boundaries are easier to test, secure and evolve.']], tradeoffs:'Model autonomy can improve flexibility while making evaluation, predictability and security harder.', exampleKind:'llm', exerciseKind:'structuredOutput' }),
    L('rag', 'Embeddings, retrieval & RAG', 25, 'Understand what retrieval adds, what it cannot guarantee, and how to evaluate it.', { visual:'rag', sources:['openaiAgents'], objectives:['Explain embeddings at a useful level.','Separate retrieval quality from generation quality.','Reason about chunking and metadata.'], mentalModel:'RAG first chooses evidence, then asks a model to answer with that evidence. A wrong answer may come from bad retrieval, bad context construction, or bad generation.', bullets:['Embeddings map items into vector representations useful for similarity search.','Chunk size trades local specificity against missing surrounding context.','Metadata filters can be as important as vector similarity.','Grounding does not eliminate hallucination; outputs still need evaluation.'], traps:[['Top-k as the only tuning knob','Indexing, chunking, filters, reranking and query rewriting all affect recall.'],['Evaluating only final prose','You need retrieval metrics or labelled evidence to diagnose the pipeline.']], tradeoffs:'Higher recall can increase context noise and cost; reranking adds latency but may improve precision.', exampleKind:'rag', exerciseKind:'retrievalEval' }),
    L('tools-agents', 'Tool calling, agents & MCP servers', 30, 'Model tool boundaries as security boundaries and understand MCP’s host/client/server shape.', { visual:'mcp', sources:['mcp','openaiAgents','openaiSafety'], objectives:['Explain MCP tools, resources and prompts.','Keep authority in the host/application.','Validate tool inputs and outputs.'], mentalModel:'MCP standardises how an AI host discovers and invokes capabilities exposed by servers. Discovery is not authorization. The host still decides what the model is allowed to call and under which user authority.', bullets:['Tools perform actions or computations; resources expose context/data; prompts provide reusable interaction templates in MCP’s model.','Treat every tool call like an API request from an untrusted planner: validate schema, identity and policy.','Use least privilege and explicit confirmation for consequential actions.','Log tool intent, arguments, result and authorization decision for auditability.'], traps:[['The MCP server decides user authority','The host/application must preserve the user’s identity, consent and policy boundaries.'],['Tool descriptions as security controls','Prompt text can guide a model but cannot replace server-side authorization.']], tradeoffs:'A richer tool surface increases capability and attack surface at the same time; expose the minimum authority needed.', exampleKind:'mcp', exerciseKind:'toolPolicy' }),
    L('ai-security-evals', 'Prompt injection, evals & AI reliability', 30, 'Assume model inputs can contain adversarial instructions and evaluate systems end-to-end.', { visual:'promptInjection', sources:['openaiSafety','owasp'], objectives:['Treat retrieved text as untrusted data.','Design capability-based tool permissions.','Build eval sets around real failure modes.'], mentalModel:'Prompt injection is an instruction/data boundary problem: the model may not reliably distinguish trusted developer intent from malicious text inside retrieved or user-provided content.', bullets:['Do not grant high-impact tools simply because the model requests them.','Separate read tools from write tools and scope credentials tightly.','Evals should measure task success and safety/failure modes, not just stylistic quality.','Human approval is valuable when the consequence is high and automation confidence is insufficient.'], traps:[['“Tell the model to ignore malicious instructions”','Prompt text alone is not a reliable security boundary.'],['Only testing happy prompts','Adversarial, ambiguous and malformed cases belong in the eval suite.']], tradeoffs:'More autonomy can increase task completion but also the cost of mistakes; architecture should scale authority with confidence and consequence.', exampleKind:'promptInjection', exerciseKind:'agentGuardrail' }),
  ]),
];

export const LANGUAGES = [
  { id: 'typescript', label: 'TypeScript', runtime: 'js' },
  { id: 'javascript', label: 'JavaScript', runtime: 'js' },
  { id: 'python', label: 'Python', runtime: 'python' },
];

export const flatLabs = () => TOPICS.flatMap((topic) => topic.labs.map((lab) => ({ ...lab, topicId: topic.id, topicTitle: topic.title })));
export const findTopic = (id) => TOPICS.find((topic) => topic.id === id);
export const findLab = (id) => flatLabs().find((lab) => lab.id === id);
