const Q = (topic, question, options, answer, explanation) => ({ topic, question, options, answer, explanation });

export const FINAL_QUIZ = [
  Q('complexity','A loop advances pointer i from 0 to n once. Inside it, pointer j also only moves forward and never resets. What is the tightest typical bound on total pointer advances?',['O(log n)','O(n)','O(n²)','O(2ⁿ)'],1,'Each pointer advances at most n times, so total movement is linear even though one loop may appear nested.'),
  Q('complexity','Which statement about amortized O(1) append to a dynamic array is most accurate?',['Every append takes constant time','Some appends can be O(n), but total work across n appends is O(n)','It is only O(1) when the array never resizes','It means average input values are random'],1,'Geometric growth causes occasional O(n) copies, but those costs are spread across many cheap appends.'),
  Q('complexity','A function returns a newly allocated array containing n transformed items and otherwise uses constant working memory. What should you say about space?',['Total O(1), auxiliary O(1)','Total O(n), auxiliary O(1) excluding output','Total O(log n), auxiliary O(n)','Total O(n²), auxiliary O(n)'],1,'The output itself is O(n); if output is excluded, the additional working memory can be O(1).'),
  Q('complexity','Why can Promise.all over 100,000 network calls be dangerous even if each operation is “O(1)”?',['Big‑O forbids parallel work','It can create unbounded in-flight work, memory pressure, and downstream overload','Promise.all makes each request O(n)','JavaScript automatically serializes the calls'],1,'System complexity includes concurrency and external capacity; call count and simultaneous pressure matter.'),

  Q('algorithms','You need repeated membership tests against a mostly static collection. Which structure is usually the best fit?',['Linked list','Hash set','Stack','Binary heap'],1,'A hash set is designed for expected constant-time membership at the cost of extra memory.'),
  Q('algorithms','When is binary search valid?',['Whenever the array is large','When the search predicate/order is monotonic over the search space','Only on integers','Only when all values are unique'],1,'Binary search relies on being able to discard one side based on an ordering/monotonic invariant.'),
  Q('algorithms','What is the time complexity of BFS over an adjacency-list graph?',['O(V)','O(E)','O(V+E)','O(V²) always'],2,'Each vertex and edge is processed a bounded number of times.'),
  Q('algorithms','Why use a heap in a priority queue?',['O(1) arbitrary deletion','O(log n) insertion and priority extraction with O(1) peek in a typical binary heap','It keeps all values fully sorted','It removes the need for comparison'],1,'A heap maintains partial order sufficient for efficient min/max access without fully sorting all elements.'),

  Q('concurrency','What is the best distinction between concurrency and parallelism?',['They are synonyms','Concurrency manages multiple in-flight tasks; parallelism executes work simultaneously','Concurrency is only threads; parallelism is only processes','Parallelism applies only to I/O'],1,'Concurrent systems interleave/manage tasks; parallel systems actually execute multiple tasks at the same instant.'),
  Q('concurrency','A read-modify-write sequence loses increments under load. What is the core issue?',['Memory leak','Race condition across a non-atomic state transition','Dead code','Backpressure'],1,'Correctness depends on timing because the full transition is not atomic.'),
  Q('concurrency','What is backpressure?',['Encrypting queued messages','A mechanism for slowing/rejecting upstream work when consumers cannot keep up','Running tasks on more CPU cores','Retrying failed requests immediately'],1,'Backpressure prevents a fast producer from overwhelming slower consumers and unbounded queues.'),
  Q('concurrency','Why is a global lock often a poor first scaling solution?',['Locks are always incorrect','It can serialize unrelated work and reduce throughput','It cannot protect shared state','It only works in Python'],1,'A global lock may preserve correctness but broadens the critical section and limits concurrency.'),

  Q('system-design','What should normally happen before drawing a large system architecture?',['Choose Kafka','Choose a database vendor','Clarify requirements, scale, latency, durability, and consistency targets','Design the cache'],2,'Architecture choices only make sense against explicit functional and non-functional requirements.'),
  Q('system-design','What is a cache stampede?',['A cache node encrypts data twice','Many clients recompute/refetch the same missing or expired value simultaneously','The cache is too large','A cache uses LRU'],1,'Simultaneous misses on a hot key can overload the backing dependency.'),
  Q('system-design','At-least-once message delivery implies what for consumers?',['Duplicates are impossible','Consumers should generally be idempotent or deduplicate effects','Messages are always ordered globally','Transactions are unnecessary'],1,'Redelivery is expected, so business effects must tolerate the same logical message more than once.'),
  Q('system-design','Why can average requests/second be misleading for capacity planning?',['Averages are mathematically invalid','Peak traffic and burstiness can exceed average capacity by a large factor','Only p50 latency matters','Databases ignore peaks'],1,'Systems must survive real peaks and bursts, not only long-window averages.'),

  Q('distributed','What does eventual consistency guarantee in the usual sense?',['Every read sees the latest write','Replicas converge if updates stop and communication continues','Writes are never lost','Network partitions cannot occur'],1,'Eventual consistency permits temporary divergence but requires convergence under suitable conditions.'),
  Q('distributed','Which statement about CAP is most accurate?',['Always pick exactly two of consistency, availability, partition tolerance','During a network partition, a distributed system must trade off stronger consistency against availability','Partition tolerance is optional on the internet','CAP describes database normalization'],1,'CAP is specifically about behaviour during partitions, not a permanent “pick two” product menu.'),
  Q('distributed','Why are idempotency keys useful for payment-style APIs?',['They make requests faster','They let retries refer to the same logical operation and avoid duplicate effects','They encrypt card data','They guarantee global serializability'],1,'A timeout leaves the caller uncertain whether the first attempt succeeded; a stable key lets the server recognise repeats.'),
  Q('distributed','What risk does asynchronous replication introduce?',['Followers can lag behind the leader','It forces every read to be linearizable','It prevents failover','It eliminates stale reads'],0,'Acknowledged data may not yet exist on followers, affecting freshness and some failover scenarios.'),

  Q('architecture','What does high cohesion mean?',['A module depends on many other modules','A module’s responsibilities belong closely together','Every function is in one file','All services share one database'],1,'Cohesion is about how strongly the responsibilities within a module relate to one another.'),
  Q('architecture','What is the main warning against premature DRY abstractions?',['Duplication is always good','Similar code may represent different concepts that need to evolve independently','Functions cannot be reused','Interfaces are too slow'],1,'Merging coincidentally similar code can couple change that should remain independent.'),
  Q('architecture','Which is a real advantage of a modular monolith?',['No need for module boundaries','Strong internal boundaries without distributed-systems overhead','Infinite horizontal scale','Independent database per function'],1,'You can retain modular design and one deployment/runtime boundary, avoiding network and operations tax.'),
  Q('architecture','Event sourcing means what?',['Publishing any event to Kafka','Using events as the source of truth from which state is derived','Using CQRS in every service','Keeping audit logs beside current state only'],1,'Event sourcing stores state changes as the authoritative event history and derives current views from it.'),

  Q('networking','Which HTTP method is defined as safe?',['POST','PATCH','GET','DELETE'],2,'GET is intended for retrieval without requested state-changing side effects.'),
  Q('networking','Which statement about PUT is generally correct?',['It is defined as idempotent','It is always cacheable','It is safe like GET','It cannot contain a body'],0,'Repeating the same PUT request is intended to have the same effect as one such request.'),
  Q('networking','When is SSE often simpler than WebSockets?',['Bidirectional multiplayer input','Server-to-browser one-way event streaming','Peer-to-peer video','Binary file uploads'],1,'SSE is a simple HTTP-based server→client stream with browser reconnection support.'),
  Q('networking','What does TLS primarily add above a transport such as TCP?',['Application authorization rules','Encryption, integrity, and peer authentication mechanisms','Database transactions','DNS resolution'],1,'TLS protects data in transit and authenticates peers; application authorization remains separate.'),

  Q('databases','Why can adding many indexes hurt write-heavy workloads?',['Indexes disable transactions','Each index consumes storage and may require maintenance on writes','Indexes force full table scans','Indexes prevent replication'],1,'Extra indexes trade read access paths for storage and write maintenance cost.'),
  Q('databases','What is MVCC intended to help with?',['Compressing backups','Managing concurrent versions so readers/writers can coexist under snapshot-style semantics','Replacing indexes','Encrypting rows'],1,'MVCC tracks versions so transactions can observe appropriate snapshots while concurrent updates proceed.'),
  Q('databases','What does serializable isolation aim to provide?',['Every query uses one CPU core','An outcome equivalent to some serial transaction order','No transaction can ever fail','All reads come from cache'],1,'Serializable execution prevents anomalies that could not happen if transactions ran one at a time in some order.'),
  Q('databases','What is a common danger of a poor partition key?',['Too much normalization','Hotspots or expensive cross-partition operations','Automatic data encryption','More local joins'],1,'Uneven key distribution or access patterns can concentrate load on a small subset of shards.'),

  Q('security','What is the strongest default defense against SQL injection in application code?',['Escaping apostrophes manually','Parameterized queries/prepared statements','Hiding database errors','Using POST instead of GET'],1,'Parameters keep untrusted values separate from SQL syntax.'),
  Q('security','What is BOLA/IDOR fundamentally about?',['Weak encryption','Missing object-level authorization checks','Slow hashing','Invalid TLS certificates'],1,'A user can access another object by manipulating an identifier when server-side authorization is missing.'),
  Q('security','Why is SSRF dangerous?',['It only causes XSS','A server may be tricked into reaching internal or privileged network destinations','It slows CSS rendering','It disables cookies'],1,'The server’s network position and credentials may grant access the external user does not have.'),
  Q('security','Which statement about authentication and authorization is correct?',['Authentication automatically grants all permissions','Authentication proves identity; authorization decides permitted actions/resources','Authorization happens only at login','They are synonyms'],1,'Identity and permission are separate decisions and both need enforcement.'),

  Q('reliability','An SLI is best described as what?',['A contractual penalty','A measured indicator of service behaviour','A retry algorithm','A deployment strategy'],1,'An SLI is the measurement; an SLO is the target and an SLA is an external agreement.'),
  Q('reliability','Why add jitter to exponential backoff?',['To encrypt retry timing','To avoid many clients retrying in lockstep','To guarantee success','To reduce request payload size'],1,'Randomness spreads retries over time and reduces synchronized retry storms.'),
  Q('reliability','What is the purpose of a circuit breaker?',['Cache database rows','Stop repeatedly calling a dependency that is clearly failing and allow recovery probing','Replace authorization','Compress logs'],1,'Circuit breakers protect resources and reduce cascading failure when a dependency is unhealthy.'),
  Q('reliability','Why are p95/p99 latency metrics useful?',['Averages are illegal','They expose slow-tail experience hidden by averages','They always equal SLOs','They measure correctness'],1,'Tail percentiles show what slower users experience even when the mean remains healthy.'),

  Q('testing','What is a strong use for an integration test?',['Testing a pure arithmetic helper','Verifying your application actually interacts correctly with a real database/queue boundary','Replacing all unit tests','Testing CSS colors'],1,'Integration tests are valuable where behaviour depends on a real external boundary or component interaction.'),
  Q('testing','What does a feature flag primarily enable?',['Automatic type checking','Separating code deployment from feature release/exposure','Database normalization','TLS termination'],1,'Flags let code exist in production while exposure is controlled independently.'),
  Q('testing','Why use expand/contract database migrations?',['To make schema files shorter','To keep old and new application versions compatible during staged rollout/rollback','To remove transactions','To avoid indexes'],1,'Backward-compatible intermediate states make rolling deployment and rollback safer.'),
  Q('testing','What is property-based testing?',['Testing only object properties/getters','Generating many inputs to verify invariants/properties rather than only hand-picked examples','A browser-only test','Snapshot testing'],1,'Property tests express general rules and search broader input spaces for counterexamples.'),

  Q('ai','Which design is safer for durable application state?',['Keep it only in the conversation prompt','Store authoritative state in deterministic application/database layers','Ask the model to remember it forever','Encode it only in embeddings'],1,'Models are probabilistic processors, not durable transactional state stores.'),
  Q('ai','In RAG, a wrong answer can originate from which layers?',['Only generation','Retrieval, context construction, or generation','Only embeddings','Only the user interface'],1,'End-to-end quality depends on selecting the right evidence and using it correctly.'),
  Q('ai','What is the correct trust model for an MCP tool call?',['The model is trusted because it selected the tool','Tool arguments should be treated as untrusted and authorized using trusted host/server identity context','Tool descriptions replace authorization','MCP guarantees safe side effects'],1,'MCP standardizes capability interaction; it does not make model-generated arguments authoritative.'),
  Q('ai','Why is “ignore malicious instructions in retrieved text” insufficient as a prompt-injection defense?',['Models cannot read text','Prompt text is not a reliable security boundary for tool authority','Retrieved text is always trusted','MCP blocks all prompt injection'],1,'Security-critical authority needs deterministic permission checks, scoped tools, validation, and sometimes user confirmation.'),
];
